// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace key.SOURCEDB.HTH000PA.HTHPA
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	using EdpSimulator;
	public partial class HTHPSE_T : IEdpRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"HTHPSE_T\",\"namespace\":\"key.SOURCEDB.HTH000PA.HTHPA\",\"fie" +
				"lds\":[{\"name\":\"IDMSGBAN_1\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"IDMSGBAN_2\",\"d" +
				"efault\":\"\",\"type\":\"string\"}]}");
		private string _IDMSGBAN_1;
		private string _IDMSGBAN_2;
		public virtual Schema Schema
		{
			get
			{
				return HTHPSE_T._SCHEMA;
			}
		}
		public string IDMSGBAN_1
		{
			get
			{
				return this._IDMSGBAN_1;
			}
			set
			{
				this._IDMSGBAN_1 = value;
			}
		}
		public string IDMSGBAN_2
		{
			get
			{
				return this._IDMSGBAN_2;
			}
			set
			{
				this._IDMSGBAN_2 = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.IDMSGBAN_1;
			case 1: return this.IDMSGBAN_2;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.IDMSGBAN_1 = (System.String)fieldValue; break;
			case 1: this.IDMSGBAN_2 = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}

		public string GetPartitionValue() => "";


		public string GetCosmosId() => "";
	}
}
