// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace @value.SOURCEDB.DEP000PA.DEPPA
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	[Serializable]
	public partial class HMV_DDA : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"HMV_DDA\",\"namespace\":\"value.SOURCEDB.DEP000PA.DEPPA\",\"fi" +
				"elds\":[{\"name\":\"HDDA_KEY_COMP\",\"default\":0,\"type\":\"int\"},{\"name\":\"HDDA_KEY_CONTA" +
				"\",\"default\":0,\"type\":\"long\"},{\"name\":\"HDDA_KEY_DATA_LANCAMENTO\",\"default\":\"\",\"ty" +
				"pe\":\"string\"},{\"name\":\"HDDA_KEY_ORIGEM\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"H" +
				"DDA_KEY_DATA_HORA\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"HDDA_HST_REVERSAL\",\"de" +
				"fault\":\"\",\"type\":\"string\"},{\"name\":\"HDDA_HST_STMT_REVERS\",\"default\":\"\",\"type\":\"s" +
				"tring\"},{\"name\":\"HDDA_HST_CURR_DG\",\"default\":0,\"type\":\"int\"},{\"name\":\"HDDA_HST_S" +
				"UBPRD\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"HDDA_HST_TRAN_SIGN\",\"default\":0,\"t" +
				"ype\":\"int\"},{\"name\":\"HDDA_HST_TRAN_TYPE\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"" +
				"HDDA_HST_GLI_SOURCE\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"HDDA_HST_FUNC_ID\",\"d" +
				"efault\":0,\"type\":\"int\"},{\"name\":\"HDDA_HST_SOURCE_TYPE\",\"default\":0,\"type\":\"int\"}" +
				",{\"name\":\"HDDA_HST_ENVIRONMENT\",\"default\":0,\"type\":\"int\"},{\"name\":\"HDDA_HST_EFF_" +
				"DATE\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"HDDA_HST_TRAN_COD_REVERS\",\"default\"" +
				":0,\"type\":\"int\"},{\"name\":\"HDDA_HST_DEP_WD\",\"default\":\"\",\"type\":\"string\"},{\"name\"" +
				":\"HDDA_HST_TAMT\",\"default\":\"0\",\"type\":\"string\"},{\"name\":\"HDDA_HST_BRANCH\",\"defau" +
				"lt\":0,\"type\":\"int\"},{\"name\":\"HDDA_HST_TRANS_SEQ\",\"default\":0,\"type\":\"int\"},{\"nam" +
				"e\":\"HDDA_HST_PAID_INTO_OD\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"HDDA_HST_LEDG_" +
				"BAL_AFP\",\"default\":\"0\",\"type\":\"string\"},{\"name\":\"HDDA_HST_COLL_BAL_AFP\",\"default" +
				"\":\"0\",\"type\":\"string\"},{\"name\":\"HDDA_HST_TRANS_NO\",\"default\":0,\"type\":\"long\"},{\"" +
				"name\":\"HDDA_HST_TCK_SERIAL_NO\",\"default\":0,\"type\":\"long\"},{\"name\":\"HDDA_HST_TRAC" +
				"E_ID\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"HDDA_HST_CASH_AMT\",\"default\":\"0\",\"t" +
				"ype\":\"string\"},{\"name\":\"HDDA_HST_INTERN_GEN\",\"default\":\"\",\"type\":\"string\"},{\"nam" +
				"e\":\"HDDA_HST_HORA\",\"default\":0,\"type\":\"int\"},{\"name\":\"HDDA_HST_DATA_SISTEMA\",\"de" +
				"fault\":\"\",\"type\":\"string\"},{\"name\":\"HDDA_HST_SOURCE\",\"default\":\"\",\"type\":\"string" +
				"\"},{\"name\":\"HDDA_HST_OPER\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"HDDA_HST_DESCR" +
				"\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"HDDA_HST_ACT_NO_TO\",\"default\":0,\"type\":" +
				"\"long\"},{\"name\":\"HDDA_HST_ACT_NO_FROM\",\"default\":0,\"type\":\"long\"},{\"name\":\"HDDA_" +
				"HST_VAMT_FLOAT_0\",\"default\":\"0\",\"type\":\"string\"},{\"name\":\"HDDA_HST_VDAY_FLOAT_0\"" +
				",\"default\":0,\"type\":\"long\"},{\"name\":\"HDDA_HST_VAMT_FLOAT_1\",\"default\":\"0\",\"type\"" +
				":\"string\"},{\"name\":\"HDDA_HST_VDAY_FLOAT_1\",\"default\":0,\"type\":\"long\"},{\"name\":\"H" +
				"DDA_HST_VAMT_FLOAT_2\",\"default\":\"0\",\"type\":\"string\"},{\"name\":\"HDDA_HST_VDAY_FLOA" +
				"T_2\",\"default\":0,\"type\":\"long\"},{\"name\":\"HDDA_HST_VAMT_FLOAT_3\",\"default\":\"0\",\"t" +
				"ype\":\"string\"},{\"name\":\"HDDA_HST_VDAY_FLOAT_3\",\"default\":0,\"type\":\"long\"},{\"name" +
				"\":\"HDDA_HST_TRACE_ID_CONT\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"HDDA_HST_INPUT" +
				"_MOEDA\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"HDDA_HST_ORIG_MOEDA\",\"default\":\"\"" +
				",\"type\":\"string\"},{\"name\":\"HDDA_HST_ORIG_CURR_TAMT\",\"default\":\"0\",\"type\":\"string" +
				"\"},{\"name\":\"HDDA_HST_ORIG_BRANCH\",\"default\":0,\"type\":\"int\"},{\"name\":\"HDDA_HST_ST" +
				"MT_REVERS_CODE\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"HDDA_HST_LIM_TOL_USADO\",\"" +
				"default\":\"0\",\"type\":\"string\"},{\"name\":\"HDDA_HST_CANAL\",\"default\":\"\",\"type\":\"stri" +
				"ng\"},{\"name\":\"HDDA_HST_ID_PRIORIT\",\"default\":0,\"type\":\"int\"},{\"name\":\"HDDA_HST_C" +
				"ANAL2\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"HDDA_HST_TRATADO\",\"default\":\"\",\"ty" +
				"pe\":\"string\"},{\"name\":\"HDDA_HST_AVAILABLE_BALANCE\",\"default\":\"0\",\"type\":\"string\"" +
				"},{\"name\":\"HDDA_HST_ADJ_BAL\",\"default\":\"0\",\"type\":\"string\"},{\"name\":\"HDDA_HST_CO" +
				"LL_BAL\",\"default\":\"0\",\"type\":\"string\"},{\"name\":\"HDDA_HST_SALDO_AUTORIZADO\",\"defa" +
				"ult\":\"0\",\"type\":\"string\"},{\"name\":\"HDDA_HST_SLD_DISP_BD\",\"default\":\"0\",\"type\":\"s" +
				"tring\"},{\"name\":\"HDDA_HST_LINE_AMT\",\"default\":\"0\",\"type\":\"string\"},{\"name\":\"HDDA" +
				"_HST_MEMO_DR\",\"default\":\"0\",\"type\":\"string\"},{\"name\":\"HDDA_HST_MEMO_CR\",\"default" +
				"\":\"0\",\"type\":\"string\"},{\"name\":\"HDDA_HST_CATIVOS_DEBITO\",\"default\":\"0\",\"type\":\"s" +
				"tring\"},{\"name\":\"HDDA_HST_CATIVOS_CREDITO\",\"default\":\"0\",\"type\":\"string\"},{\"name" +
				"\":\"HDDA_HST_SLD_DISP_LCA\",\"default\":\"0\",\"type\":\"string\"},{\"name\":\"HDDA_HST_INVES" +
				"TMENT_BAL\",\"default\":\"0\",\"type\":\"string\"},{\"name\":\"HDDA_HST_AVAIL_LOC\",\"default\"" +
				":\"0\",\"type\":\"string\"},{\"name\":\"HDDA_HST_SSV_LIM_AUTORIZ\",\"default\":\"0\",\"type\":\"s" +
				"tring\"},{\"name\":\"HDDA_HST_SLD_CONTAB\",\"default\":\"0\",\"type\":\"string\"},{\"name\":\"HD" +
				"DA_HST_DESCR_CONT\",\"default\":\"\",\"type\":\"string\"}]}");
		private int _HDDA_KEY_COMP;
		private long _HDDA_KEY_CONTA;
		private string _HDDA_KEY_DATA_LANCAMENTO;
		private string _HDDA_KEY_ORIGEM;
		private string _HDDA_KEY_DATA_HORA;
		private string _HDDA_HST_REVERSAL;
		private string _HDDA_HST_STMT_REVERS;
		private int _HDDA_HST_CURR_DG;
		private string _HDDA_HST_SUBPRD;
		private int _HDDA_HST_TRAN_SIGN;
		private string _HDDA_HST_TRAN_TYPE;
		private string _HDDA_HST_GLI_SOURCE;
		private int _HDDA_HST_FUNC_ID;
		private int _HDDA_HST_SOURCE_TYPE;
		private int _HDDA_HST_ENVIRONMENT;
		private string _HDDA_HST_EFF_DATE;
		private int _HDDA_HST_TRAN_COD_REVERS;
		private string _HDDA_HST_DEP_WD;
		private string _HDDA_HST_TAMT;
		private int _HDDA_HST_BRANCH;
		private int _HDDA_HST_TRANS_SEQ;
		private string _HDDA_HST_PAID_INTO_OD;
		private string _HDDA_HST_LEDG_BAL_AFP;
		private string _HDDA_HST_COLL_BAL_AFP;
		private long _HDDA_HST_TRANS_NO;
		private long _HDDA_HST_TCK_SERIAL_NO;
		private string _HDDA_HST_TRACE_ID;
		private string _HDDA_HST_CASH_AMT;
		private string _HDDA_HST_INTERN_GEN;
		private int _HDDA_HST_HORA;
		private string _HDDA_HST_DATA_SISTEMA;
		private string _HDDA_HST_SOURCE;
		private string _HDDA_HST_OPER;
		private string _HDDA_HST_DESCR;
		private long _HDDA_HST_ACT_NO_TO;
		private long _HDDA_HST_ACT_NO_FROM;
		private string _HDDA_HST_VAMT_FLOAT_0;
		private long _HDDA_HST_VDAY_FLOAT_0;
		private string _HDDA_HST_VAMT_FLOAT_1;
		private long _HDDA_HST_VDAY_FLOAT_1;
		private string _HDDA_HST_VAMT_FLOAT_2;
		private long _HDDA_HST_VDAY_FLOAT_2;
		private string _HDDA_HST_VAMT_FLOAT_3;
		private long _HDDA_HST_VDAY_FLOAT_3;
		private string _HDDA_HST_TRACE_ID_CONT;
		private string _HDDA_HST_INPUT_MOEDA;
		private string _HDDA_HST_ORIG_MOEDA;
		private string _HDDA_HST_ORIG_CURR_TAMT;
		private int _HDDA_HST_ORIG_BRANCH;
		private string _HDDA_HST_STMT_REVERS_CODE;
		private string _HDDA_HST_LIM_TOL_USADO;
		private string _HDDA_HST_CANAL;
		private int _HDDA_HST_ID_PRIORIT;
		private string _HDDA_HST_CANAL2;
		private string _HDDA_HST_TRATADO;
		private string _HDDA_HST_AVAILABLE_BALANCE;
		private string _HDDA_HST_ADJ_BAL;
		private string _HDDA_HST_COLL_BAL;
		private string _HDDA_HST_SALDO_AUTORIZADO;
		private string _HDDA_HST_SLD_DISP_BD;
		private string _HDDA_HST_LINE_AMT;
		private string _HDDA_HST_MEMO_DR;
		private string _HDDA_HST_MEMO_CR;
		private string _HDDA_HST_CATIVOS_DEBITO;
		private string _HDDA_HST_CATIVOS_CREDITO;
		private string _HDDA_HST_SLD_DISP_LCA;
		private string _HDDA_HST_INVESTMENT_BAL;
		private string _HDDA_HST_AVAIL_LOC;
		private string _HDDA_HST_SSV_LIM_AUTORIZ;
		private string _HDDA_HST_SLD_CONTAB;
		private string _HDDA_HST_DESCR_CONT;
		public virtual Schema Schema
		{
			get
			{
				return HMV_DDA._SCHEMA;
			}
		}
		public int HDDA_KEY_COMP
		{
			get
			{
				return this._HDDA_KEY_COMP;
			}
			set
			{
				this._HDDA_KEY_COMP = value;
			}
		}
		public long HDDA_KEY_CONTA
		{
			get
			{
				return this._HDDA_KEY_CONTA;
			}
			set
			{
				this._HDDA_KEY_CONTA = value;
			}
		}
		public string HDDA_KEY_DATA_LANCAMENTO
		{
			get
			{
				return this._HDDA_KEY_DATA_LANCAMENTO;
			}
			set
			{
				this._HDDA_KEY_DATA_LANCAMENTO = value;
			}
		}
		public string HDDA_KEY_ORIGEM
		{
			get
			{
				return this._HDDA_KEY_ORIGEM;
			}
			set
			{
				this._HDDA_KEY_ORIGEM = value;
			}
		}
		public string HDDA_KEY_DATA_HORA
		{
			get
			{
				return this._HDDA_KEY_DATA_HORA;
			}
			set
			{
				this._HDDA_KEY_DATA_HORA = value;
			}
		}
		public string HDDA_HST_REVERSAL
		{
			get
			{
				return this._HDDA_HST_REVERSAL;
			}
			set
			{
				this._HDDA_HST_REVERSAL = value;
			}
		}
		public string HDDA_HST_STMT_REVERS
		{
			get
			{
				return this._HDDA_HST_STMT_REVERS;
			}
			set
			{
				this._HDDA_HST_STMT_REVERS = value;
			}
		}
		public int HDDA_HST_CURR_DG
		{
			get
			{
				return this._HDDA_HST_CURR_DG;
			}
			set
			{
				this._HDDA_HST_CURR_DG = value;
			}
		}
		public string HDDA_HST_SUBPRD
		{
			get
			{
				return this._HDDA_HST_SUBPRD;
			}
			set
			{
				this._HDDA_HST_SUBPRD = value;
			}
		}
		public int HDDA_HST_TRAN_SIGN
		{
			get
			{
				return this._HDDA_HST_TRAN_SIGN;
			}
			set
			{
				this._HDDA_HST_TRAN_SIGN = value;
			}
		}
		public string HDDA_HST_TRAN_TYPE
		{
			get
			{
				return this._HDDA_HST_TRAN_TYPE;
			}
			set
			{
				this._HDDA_HST_TRAN_TYPE = value;
			}
		}
		public string HDDA_HST_GLI_SOURCE
		{
			get
			{
				return this._HDDA_HST_GLI_SOURCE;
			}
			set
			{
				this._HDDA_HST_GLI_SOURCE = value;
			}
		}
		public int HDDA_HST_FUNC_ID
		{
			get
			{
				return this._HDDA_HST_FUNC_ID;
			}
			set
			{
				this._HDDA_HST_FUNC_ID = value;
			}
		}
		public int HDDA_HST_SOURCE_TYPE
		{
			get
			{
				return this._HDDA_HST_SOURCE_TYPE;
			}
			set
			{
				this._HDDA_HST_SOURCE_TYPE = value;
			}
		}
		public int HDDA_HST_ENVIRONMENT
		{
			get
			{
				return this._HDDA_HST_ENVIRONMENT;
			}
			set
			{
				this._HDDA_HST_ENVIRONMENT = value;
			}
		}
		public string HDDA_HST_EFF_DATE
		{
			get
			{
				return this._HDDA_HST_EFF_DATE;
			}
			set
			{
				this._HDDA_HST_EFF_DATE = value;
			}
		}
		public int HDDA_HST_TRAN_COD_REVERS
		{
			get
			{
				return this._HDDA_HST_TRAN_COD_REVERS;
			}
			set
			{
				this._HDDA_HST_TRAN_COD_REVERS = value;
			}
		}
		public string HDDA_HST_DEP_WD
		{
			get
			{
				return this._HDDA_HST_DEP_WD;
			}
			set
			{
				this._HDDA_HST_DEP_WD = value;
			}
		}
		public string HDDA_HST_TAMT
		{
			get
			{
				return this._HDDA_HST_TAMT;
			}
			set
			{
				this._HDDA_HST_TAMT = value;
			}
		}
		public int HDDA_HST_BRANCH
		{
			get
			{
				return this._HDDA_HST_BRANCH;
			}
			set
			{
				this._HDDA_HST_BRANCH = value;
			}
		}
		public int HDDA_HST_TRANS_SEQ
		{
			get
			{
				return this._HDDA_HST_TRANS_SEQ;
			}
			set
			{
				this._HDDA_HST_TRANS_SEQ = value;
			}
		}
		public string HDDA_HST_PAID_INTO_OD
		{
			get
			{
				return this._HDDA_HST_PAID_INTO_OD;
			}
			set
			{
				this._HDDA_HST_PAID_INTO_OD = value;
			}
		}
		public string HDDA_HST_LEDG_BAL_AFP
		{
			get
			{
				return this._HDDA_HST_LEDG_BAL_AFP;
			}
			set
			{
				this._HDDA_HST_LEDG_BAL_AFP = value;
			}
		}
		public string HDDA_HST_COLL_BAL_AFP
		{
			get
			{
				return this._HDDA_HST_COLL_BAL_AFP;
			}
			set
			{
				this._HDDA_HST_COLL_BAL_AFP = value;
			}
		}
		public long HDDA_HST_TRANS_NO
		{
			get
			{
				return this._HDDA_HST_TRANS_NO;
			}
			set
			{
				this._HDDA_HST_TRANS_NO = value;
			}
		}
		public long HDDA_HST_TCK_SERIAL_NO
		{
			get
			{
				return this._HDDA_HST_TCK_SERIAL_NO;
			}
			set
			{
				this._HDDA_HST_TCK_SERIAL_NO = value;
			}
		}
		public string HDDA_HST_TRACE_ID
		{
			get
			{
				return this._HDDA_HST_TRACE_ID;
			}
			set
			{
				this._HDDA_HST_TRACE_ID = value;
			}
		}
		public string HDDA_HST_CASH_AMT
		{
			get
			{
				return this._HDDA_HST_CASH_AMT;
			}
			set
			{
				this._HDDA_HST_CASH_AMT = value;
			}
		}
		public string HDDA_HST_INTERN_GEN
		{
			get
			{
				return this._HDDA_HST_INTERN_GEN;
			}
			set
			{
				this._HDDA_HST_INTERN_GEN = value;
			}
		}
		public int HDDA_HST_HORA
		{
			get
			{
				return this._HDDA_HST_HORA;
			}
			set
			{
				this._HDDA_HST_HORA = value;
			}
		}
		public string HDDA_HST_DATA_SISTEMA
		{
			get
			{
				return this._HDDA_HST_DATA_SISTEMA;
			}
			set
			{
				this._HDDA_HST_DATA_SISTEMA = value;
			}
		}
		public string HDDA_HST_SOURCE
		{
			get
			{
				return this._HDDA_HST_SOURCE;
			}
			set
			{
				this._HDDA_HST_SOURCE = value;
			}
		}
		public string HDDA_HST_OPER
		{
			get
			{
				return this._HDDA_HST_OPER;
			}
			set
			{
				this._HDDA_HST_OPER = value;
			}
		}
		public string HDDA_HST_DESCR
		{
			get
			{
				return this._HDDA_HST_DESCR;
			}
			set
			{
				this._HDDA_HST_DESCR = value;
			}
		}
		public long HDDA_HST_ACT_NO_TO
		{
			get
			{
				return this._HDDA_HST_ACT_NO_TO;
			}
			set
			{
				this._HDDA_HST_ACT_NO_TO = value;
			}
		}
		public long HDDA_HST_ACT_NO_FROM
		{
			get
			{
				return this._HDDA_HST_ACT_NO_FROM;
			}
			set
			{
				this._HDDA_HST_ACT_NO_FROM = value;
			}
		}
		public string HDDA_HST_VAMT_FLOAT_0
		{
			get
			{
				return this._HDDA_HST_VAMT_FLOAT_0;
			}
			set
			{
				this._HDDA_HST_VAMT_FLOAT_0 = value;
			}
		}
		public long HDDA_HST_VDAY_FLOAT_0
		{
			get
			{
				return this._HDDA_HST_VDAY_FLOAT_0;
			}
			set
			{
				this._HDDA_HST_VDAY_FLOAT_0 = value;
			}
		}
		public string HDDA_HST_VAMT_FLOAT_1
		{
			get
			{
				return this._HDDA_HST_VAMT_FLOAT_1;
			}
			set
			{
				this._HDDA_HST_VAMT_FLOAT_1 = value;
			}
		}
		public long HDDA_HST_VDAY_FLOAT_1
		{
			get
			{
				return this._HDDA_HST_VDAY_FLOAT_1;
			}
			set
			{
				this._HDDA_HST_VDAY_FLOAT_1 = value;
			}
		}
		public string HDDA_HST_VAMT_FLOAT_2
		{
			get
			{
				return this._HDDA_HST_VAMT_FLOAT_2;
			}
			set
			{
				this._HDDA_HST_VAMT_FLOAT_2 = value;
			}
		}
		public long HDDA_HST_VDAY_FLOAT_2
		{
			get
			{
				return this._HDDA_HST_VDAY_FLOAT_2;
			}
			set
			{
				this._HDDA_HST_VDAY_FLOAT_2 = value;
			}
		}
		public string HDDA_HST_VAMT_FLOAT_3
		{
			get
			{
				return this._HDDA_HST_VAMT_FLOAT_3;
			}
			set
			{
				this._HDDA_HST_VAMT_FLOAT_3 = value;
			}
		}
		public long HDDA_HST_VDAY_FLOAT_3
		{
			get
			{
				return this._HDDA_HST_VDAY_FLOAT_3;
			}
			set
			{
				this._HDDA_HST_VDAY_FLOAT_3 = value;
			}
		}
		public string HDDA_HST_TRACE_ID_CONT
		{
			get
			{
				return this._HDDA_HST_TRACE_ID_CONT;
			}
			set
			{
				this._HDDA_HST_TRACE_ID_CONT = value;
			}
		}
		public string HDDA_HST_INPUT_MOEDA
		{
			get
			{
				return this._HDDA_HST_INPUT_MOEDA;
			}
			set
			{
				this._HDDA_HST_INPUT_MOEDA = value;
			}
		}
		public string HDDA_HST_ORIG_MOEDA
		{
			get
			{
				return this._HDDA_HST_ORIG_MOEDA;
			}
			set
			{
				this._HDDA_HST_ORIG_MOEDA = value;
			}
		}
		public string HDDA_HST_ORIG_CURR_TAMT
		{
			get
			{
				return this._HDDA_HST_ORIG_CURR_TAMT;
			}
			set
			{
				this._HDDA_HST_ORIG_CURR_TAMT = value;
			}
		}
		public int HDDA_HST_ORIG_BRANCH
		{
			get
			{
				return this._HDDA_HST_ORIG_BRANCH;
			}
			set
			{
				this._HDDA_HST_ORIG_BRANCH = value;
			}
		}
		public string HDDA_HST_STMT_REVERS_CODE
		{
			get
			{
				return this._HDDA_HST_STMT_REVERS_CODE;
			}
			set
			{
				this._HDDA_HST_STMT_REVERS_CODE = value;
			}
		}
		public string HDDA_HST_LIM_TOL_USADO
		{
			get
			{
				return this._HDDA_HST_LIM_TOL_USADO;
			}
			set
			{
				this._HDDA_HST_LIM_TOL_USADO = value;
			}
		}
		public string HDDA_HST_CANAL
		{
			get
			{
				return this._HDDA_HST_CANAL;
			}
			set
			{
				this._HDDA_HST_CANAL = value;
			}
		}
		public int HDDA_HST_ID_PRIORIT
		{
			get
			{
				return this._HDDA_HST_ID_PRIORIT;
			}
			set
			{
				this._HDDA_HST_ID_PRIORIT = value;
			}
		}
		public string HDDA_HST_CANAL2
		{
			get
			{
				return this._HDDA_HST_CANAL2;
			}
			set
			{
				this._HDDA_HST_CANAL2 = value;
			}
		}
		public string HDDA_HST_TRATADO
		{
			get
			{
				return this._HDDA_HST_TRATADO;
			}
			set
			{
				this._HDDA_HST_TRATADO = value;
			}
		}
		public string HDDA_HST_AVAILABLE_BALANCE
		{
			get
			{
				return this._HDDA_HST_AVAILABLE_BALANCE;
			}
			set
			{
				this._HDDA_HST_AVAILABLE_BALANCE = value;
			}
		}
		public string HDDA_HST_ADJ_BAL
		{
			get
			{
				return this._HDDA_HST_ADJ_BAL;
			}
			set
			{
				this._HDDA_HST_ADJ_BAL = value;
			}
		}
		public string HDDA_HST_COLL_BAL
		{
			get
			{
				return this._HDDA_HST_COLL_BAL;
			}
			set
			{
				this._HDDA_HST_COLL_BAL = value;
			}
		}
		public string HDDA_HST_SALDO_AUTORIZADO
		{
			get
			{
				return this._HDDA_HST_SALDO_AUTORIZADO;
			}
			set
			{
				this._HDDA_HST_SALDO_AUTORIZADO = value;
			}
		}
		public string HDDA_HST_SLD_DISP_BD
		{
			get
			{
				return this._HDDA_HST_SLD_DISP_BD;
			}
			set
			{
				this._HDDA_HST_SLD_DISP_BD = value;
			}
		}
		public string HDDA_HST_LINE_AMT
		{
			get
			{
				return this._HDDA_HST_LINE_AMT;
			}
			set
			{
				this._HDDA_HST_LINE_AMT = value;
			}
		}
		public string HDDA_HST_MEMO_DR
		{
			get
			{
				return this._HDDA_HST_MEMO_DR;
			}
			set
			{
				this._HDDA_HST_MEMO_DR = value;
			}
		}
		public string HDDA_HST_MEMO_CR
		{
			get
			{
				return this._HDDA_HST_MEMO_CR;
			}
			set
			{
				this._HDDA_HST_MEMO_CR = value;
			}
		}
		public string HDDA_HST_CATIVOS_DEBITO
		{
			get
			{
				return this._HDDA_HST_CATIVOS_DEBITO;
			}
			set
			{
				this._HDDA_HST_CATIVOS_DEBITO = value;
			}
		}
		public string HDDA_HST_CATIVOS_CREDITO
		{
			get
			{
				return this._HDDA_HST_CATIVOS_CREDITO;
			}
			set
			{
				this._HDDA_HST_CATIVOS_CREDITO = value;
			}
		}
		public string HDDA_HST_SLD_DISP_LCA
		{
			get
			{
				return this._HDDA_HST_SLD_DISP_LCA;
			}
			set
			{
				this._HDDA_HST_SLD_DISP_LCA = value;
			}
		}
		public string HDDA_HST_INVESTMENT_BAL
		{
			get
			{
				return this._HDDA_HST_INVESTMENT_BAL;
			}
			set
			{
				this._HDDA_HST_INVESTMENT_BAL = value;
			}
		}
		public string HDDA_HST_AVAIL_LOC
		{
			get
			{
				return this._HDDA_HST_AVAIL_LOC;
			}
			set
			{
				this._HDDA_HST_AVAIL_LOC = value;
			}
		}
		public string HDDA_HST_SSV_LIM_AUTORIZ
		{
			get
			{
				return this._HDDA_HST_SSV_LIM_AUTORIZ;
			}
			set
			{
				this._HDDA_HST_SSV_LIM_AUTORIZ = value;
			}
		}
		public string HDDA_HST_SLD_CONTAB
		{
			get
			{
				return this._HDDA_HST_SLD_CONTAB;
			}
			set
			{
				this._HDDA_HST_SLD_CONTAB = value;
			}
		}
		public string HDDA_HST_DESCR_CONT
		{
			get
			{
				return this._HDDA_HST_DESCR_CONT;
			}
			set
			{
				this._HDDA_HST_DESCR_CONT = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.HDDA_KEY_COMP;
			case 1: return this.HDDA_KEY_CONTA;
			case 2: return this.HDDA_KEY_DATA_LANCAMENTO;
			case 3: return this.HDDA_KEY_ORIGEM;
			case 4: return this.HDDA_KEY_DATA_HORA;
			case 5: return this.HDDA_HST_REVERSAL;
			case 6: return this.HDDA_HST_STMT_REVERS;
			case 7: return this.HDDA_HST_CURR_DG;
			case 8: return this.HDDA_HST_SUBPRD;
			case 9: return this.HDDA_HST_TRAN_SIGN;
			case 10: return this.HDDA_HST_TRAN_TYPE;
			case 11: return this.HDDA_HST_GLI_SOURCE;
			case 12: return this.HDDA_HST_FUNC_ID;
			case 13: return this.HDDA_HST_SOURCE_TYPE;
			case 14: return this.HDDA_HST_ENVIRONMENT;
			case 15: return this.HDDA_HST_EFF_DATE;
			case 16: return this.HDDA_HST_TRAN_COD_REVERS;
			case 17: return this.HDDA_HST_DEP_WD;
			case 18: return this.HDDA_HST_TAMT;
			case 19: return this.HDDA_HST_BRANCH;
			case 20: return this.HDDA_HST_TRANS_SEQ;
			case 21: return this.HDDA_HST_PAID_INTO_OD;
			case 22: return this.HDDA_HST_LEDG_BAL_AFP;
			case 23: return this.HDDA_HST_COLL_BAL_AFP;
			case 24: return this.HDDA_HST_TRANS_NO;
			case 25: return this.HDDA_HST_TCK_SERIAL_NO;
			case 26: return this.HDDA_HST_TRACE_ID;
			case 27: return this.HDDA_HST_CASH_AMT;
			case 28: return this.HDDA_HST_INTERN_GEN;
			case 29: return this.HDDA_HST_HORA;
			case 30: return this.HDDA_HST_DATA_SISTEMA;
			case 31: return this.HDDA_HST_SOURCE;
			case 32: return this.HDDA_HST_OPER;
			case 33: return this.HDDA_HST_DESCR;
			case 34: return this.HDDA_HST_ACT_NO_TO;
			case 35: return this.HDDA_HST_ACT_NO_FROM;
			case 36: return this.HDDA_HST_VAMT_FLOAT_0;
			case 37: return this.HDDA_HST_VDAY_FLOAT_0;
			case 38: return this.HDDA_HST_VAMT_FLOAT_1;
			case 39: return this.HDDA_HST_VDAY_FLOAT_1;
			case 40: return this.HDDA_HST_VAMT_FLOAT_2;
			case 41: return this.HDDA_HST_VDAY_FLOAT_2;
			case 42: return this.HDDA_HST_VAMT_FLOAT_3;
			case 43: return this.HDDA_HST_VDAY_FLOAT_3;
			case 44: return this.HDDA_HST_TRACE_ID_CONT;
			case 45: return this.HDDA_HST_INPUT_MOEDA;
			case 46: return this.HDDA_HST_ORIG_MOEDA;
			case 47: return this.HDDA_HST_ORIG_CURR_TAMT;
			case 48: return this.HDDA_HST_ORIG_BRANCH;
			case 49: return this.HDDA_HST_STMT_REVERS_CODE;
			case 50: return this.HDDA_HST_LIM_TOL_USADO;
			case 51: return this.HDDA_HST_CANAL;
			case 52: return this.HDDA_HST_ID_PRIORIT;
			case 53: return this.HDDA_HST_CANAL2;
			case 54: return this.HDDA_HST_TRATADO;
			case 55: return this.HDDA_HST_AVAILABLE_BALANCE;
			case 56: return this.HDDA_HST_ADJ_BAL;
			case 57: return this.HDDA_HST_COLL_BAL;
			case 58: return this.HDDA_HST_SALDO_AUTORIZADO;
			case 59: return this.HDDA_HST_SLD_DISP_BD;
			case 60: return this.HDDA_HST_LINE_AMT;
			case 61: return this.HDDA_HST_MEMO_DR;
			case 62: return this.HDDA_HST_MEMO_CR;
			case 63: return this.HDDA_HST_CATIVOS_DEBITO;
			case 64: return this.HDDA_HST_CATIVOS_CREDITO;
			case 65: return this.HDDA_HST_SLD_DISP_LCA;
			case 66: return this.HDDA_HST_INVESTMENT_BAL;
			case 67: return this.HDDA_HST_AVAIL_LOC;
			case 68: return this.HDDA_HST_SSV_LIM_AUTORIZ;
			case 69: return this.HDDA_HST_SLD_CONTAB;
			case 70: return this.HDDA_HST_DESCR_CONT;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.HDDA_KEY_COMP = (System.Int32)fieldValue; break;
			case 1: this.HDDA_KEY_CONTA = (System.Int64)fieldValue; break;
			case 2: this.HDDA_KEY_DATA_LANCAMENTO = (System.String)fieldValue; break;
			case 3: this.HDDA_KEY_ORIGEM = (System.String)fieldValue; break;
			case 4: this.HDDA_KEY_DATA_HORA = (System.String)fieldValue; break;
			case 5: this.HDDA_HST_REVERSAL = (System.String)fieldValue; break;
			case 6: this.HDDA_HST_STMT_REVERS = (System.String)fieldValue; break;
			case 7: this.HDDA_HST_CURR_DG = (System.Int32)fieldValue; break;
			case 8: this.HDDA_HST_SUBPRD = (System.String)fieldValue; break;
			case 9: this.HDDA_HST_TRAN_SIGN = (System.Int32)fieldValue; break;
			case 10: this.HDDA_HST_TRAN_TYPE = (System.String)fieldValue; break;
			case 11: this.HDDA_HST_GLI_SOURCE = (System.String)fieldValue; break;
			case 12: this.HDDA_HST_FUNC_ID = (System.Int32)fieldValue; break;
			case 13: this.HDDA_HST_SOURCE_TYPE = (System.Int32)fieldValue; break;
			case 14: this.HDDA_HST_ENVIRONMENT = (System.Int32)fieldValue; break;
			case 15: this.HDDA_HST_EFF_DATE = (System.String)fieldValue; break;
			case 16: this.HDDA_HST_TRAN_COD_REVERS = (System.Int32)fieldValue; break;
			case 17: this.HDDA_HST_DEP_WD = (System.String)fieldValue; break;
			case 18: this.HDDA_HST_TAMT = (System.String)fieldValue; break;
			case 19: this.HDDA_HST_BRANCH = (System.Int32)fieldValue; break;
			case 20: this.HDDA_HST_TRANS_SEQ = (System.Int32)fieldValue; break;
			case 21: this.HDDA_HST_PAID_INTO_OD = (System.String)fieldValue; break;
			case 22: this.HDDA_HST_LEDG_BAL_AFP = (System.String)fieldValue; break;
			case 23: this.HDDA_HST_COLL_BAL_AFP = (System.String)fieldValue; break;
			case 24: this.HDDA_HST_TRANS_NO = (System.Int64)fieldValue; break;
			case 25: this.HDDA_HST_TCK_SERIAL_NO = (System.Int64)fieldValue; break;
			case 26: this.HDDA_HST_TRACE_ID = (System.String)fieldValue; break;
			case 27: this.HDDA_HST_CASH_AMT = (System.String)fieldValue; break;
			case 28: this.HDDA_HST_INTERN_GEN = (System.String)fieldValue; break;
			case 29: this.HDDA_HST_HORA = (System.Int32)fieldValue; break;
			case 30: this.HDDA_HST_DATA_SISTEMA = (System.String)fieldValue; break;
			case 31: this.HDDA_HST_SOURCE = (System.String)fieldValue; break;
			case 32: this.HDDA_HST_OPER = (System.String)fieldValue; break;
			case 33: this.HDDA_HST_DESCR = (System.String)fieldValue; break;
			case 34: this.HDDA_HST_ACT_NO_TO = (System.Int64)fieldValue; break;
			case 35: this.HDDA_HST_ACT_NO_FROM = (System.Int64)fieldValue; break;
			case 36: this.HDDA_HST_VAMT_FLOAT_0 = (System.String)fieldValue; break;
			case 37: this.HDDA_HST_VDAY_FLOAT_0 = (System.Int64)fieldValue; break;
			case 38: this.HDDA_HST_VAMT_FLOAT_1 = (System.String)fieldValue; break;
			case 39: this.HDDA_HST_VDAY_FLOAT_1 = (System.Int64)fieldValue; break;
			case 40: this.HDDA_HST_VAMT_FLOAT_2 = (System.String)fieldValue; break;
			case 41: this.HDDA_HST_VDAY_FLOAT_2 = (System.Int64)fieldValue; break;
			case 42: this.HDDA_HST_VAMT_FLOAT_3 = (System.String)fieldValue; break;
			case 43: this.HDDA_HST_VDAY_FLOAT_3 = (System.Int64)fieldValue; break;
			case 44: this.HDDA_HST_TRACE_ID_CONT = (System.String)fieldValue; break;
			case 45: this.HDDA_HST_INPUT_MOEDA = (System.String)fieldValue; break;
			case 46: this.HDDA_HST_ORIG_MOEDA = (System.String)fieldValue; break;
			case 47: this.HDDA_HST_ORIG_CURR_TAMT = (System.String)fieldValue; break;
			case 48: this.HDDA_HST_ORIG_BRANCH = (System.Int32)fieldValue; break;
			case 49: this.HDDA_HST_STMT_REVERS_CODE = (System.String)fieldValue; break;
			case 50: this.HDDA_HST_LIM_TOL_USADO = (System.String)fieldValue; break;
			case 51: this.HDDA_HST_CANAL = (System.String)fieldValue; break;
			case 52: this.HDDA_HST_ID_PRIORIT = (System.Int32)fieldValue; break;
			case 53: this.HDDA_HST_CANAL2 = (System.String)fieldValue; break;
			case 54: this.HDDA_HST_TRATADO = (System.String)fieldValue; break;
			case 55: this.HDDA_HST_AVAILABLE_BALANCE = (System.String)fieldValue; break;
			case 56: this.HDDA_HST_ADJ_BAL = (System.String)fieldValue; break;
			case 57: this.HDDA_HST_COLL_BAL = (System.String)fieldValue; break;
			case 58: this.HDDA_HST_SALDO_AUTORIZADO = (System.String)fieldValue; break;
			case 59: this.HDDA_HST_SLD_DISP_BD = (System.String)fieldValue; break;
			case 60: this.HDDA_HST_LINE_AMT = (System.String)fieldValue; break;
			case 61: this.HDDA_HST_MEMO_DR = (System.String)fieldValue; break;
			case 62: this.HDDA_HST_MEMO_CR = (System.String)fieldValue; break;
			case 63: this.HDDA_HST_CATIVOS_DEBITO = (System.String)fieldValue; break;
			case 64: this.HDDA_HST_CATIVOS_CREDITO = (System.String)fieldValue; break;
			case 65: this.HDDA_HST_SLD_DISP_LCA = (System.String)fieldValue; break;
			case 66: this.HDDA_HST_INVESTMENT_BAL = (System.String)fieldValue; break;
			case 67: this.HDDA_HST_AVAIL_LOC = (System.String)fieldValue; break;
			case 68: this.HDDA_HST_SSV_LIM_AUTORIZ = (System.String)fieldValue; break;
			case 69: this.HDDA_HST_SLD_CONTAB = (System.String)fieldValue; break;
			case 70: this.HDDA_HST_DESCR_CONT = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
