// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EdpSimulator.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class categoryKey : IEdpRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"categoryKey\",\"namespace\":\"EdpSimulator.Entities\",\"fields" +
				"\":[{\"name\":\"transactionid\",\"type\":\"string\"},{\"name\":\"accountid\",\"type\":\"string\"}" +
				"]}");
		private string _transactionid;
		private string _accountid;
		public virtual Schema Schema
		{
			get
			{
				return categoryKey._SCHEMA;
			}
		}
		public string transactionid
		{
			get
			{
				return this._transactionid;
			}
			set
			{
				this._transactionid = value;
			}
		}
		public string accountid
		{
			get
			{
				return this._accountid;
			}
			set
			{
				this._accountid = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.transactionid;
			case 1: return this.accountid;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.transactionid = (System.String)fieldValue; break;
			case 1: this.accountid = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}

		public string GetPartitionValue() => "";


		public string GetCosmosId() => "";
	}
}
