// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EdpSimulator.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class AfterImageH2h : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"AfterImageH2h\",\"namespace\":\"EdpSimulator.Entities\",\"fields\"" +
				":[{\"name\":\"IDMSGBAN_1\",\"type\":\"int\"},{\"name\":\"IDMSGBAN_2\",\"type\":\"int\"},{\"name\":" +
				"\"CONTA_CLI\",\"type\":\"int\"},{\"name\":\"CODMSG_BS\",\"type\":\"string\"},{\"name\":\"VERMSG\"," +
				"\"type\":\"int\"},{\"name\":\"DHMSG\",\"type\":\"int\"},{\"name\":\"CODRESPS\",\"type\":\"int\"},{\"n" +
				"ame\":\"DT_RECOLHA\",\"type\":\"int\"},{\"name\":\"ESTADO_ANT\",\"type\":\"string\"},{\"name\":\"E" +
				"STADO_ACT\",\"type\":\"string\"},{\"name\":\"RETURN_CODE\",\"type\":\"int\"},{\"name\":\"RETURN_" +
				"MSG\",\"type\":\"string\"},{\"name\":\"TIPO_PEDIDO\",\"type\":\"int\"},{\"name\":\"TIP_PAG_SER\"," +
				"\"type\":\"int\"},{\"name\":\"NIB_ORD\",\"type\":\"string\"},{\"name\":\"ENTIDADE\",\"type\":\"int\"" +
				"},{\"name\":\"REFERENCIA\",\"type\":\"int\"},{\"name\":\"REF_ESP\",\"type\":\"int\"},{\"name\":\"RE" +
				"F_ADICIONAL\",\"type\":\"int\"},{\"name\":\"REF_RESPOSTA\",\"type\":\"int\"},{\"name\":\"MONTANT" +
				"E\",\"type\":\"string\"},{\"name\":\"REDE_ORIGEM\",\"type\":\"string\"},{\"name\":\"CANAL_ORIGEM" +
				"\",\"type\":\"string\"},{\"name\":\"USERID_CLI\",\"type\":\"string\"},{\"name\":\"CAT_NR\",\"type\"" +
				":\"string\"},{\"name\":\"CAT_CARTAO\",\"type\":\"string\"},{\"name\":\"LOCMORTER\",\"type\":\"str" +
				"ing\"},{\"name\":\"CHAVE_TRF\",\"type\":\"string\"},{\"name\":\"APLIC_N\",\"type\":\"string\"},{\"" +
				"name\":\"ID_LOG_SIBS\",\"type\":\"int\"},{\"name\":\"NR_LOG_SIBS\",\"type\":\"int\"},{\"name\":\"N" +
				"R_CONTRIBUINTE\",\"type\":\"int\"},{\"name\":\"NR_FACTURA\",\"type\":\"int\"},{\"name\":\"DESCEN" +
				"T\",\"type\":\"string\"},{\"name\":\"TIPSER\",\"type\":\"int\"},{\"name\":\"CODMOEDA\",\"type\":\"st" +
				"ring\"},{\"name\":\"CODRECS\",\"type\":\"string\"},{\"name\":\"RESP1\",\"type\":\"string\"},{\"nam" +
				"e\":\"RESP2\",\"type\":\"string\"},{\"name\":\"BANCO_CLI\",\"type\":\"int\"},{\"name\":\"BALCAO_CL" +
				"I\",\"type\":\"int\"},{\"name\":\"CKD_CLI\",\"type\":\"int\"},{\"name\":\"DH_INS\",\"type\":\"string" +
				"\"},{\"name\":\"CONFIRMACAO_SIBS\",\"type\":\"string\"},{\"name\":\"DH_CONFIRMACAO\",\"type\":\"" +
				"string\"},{\"name\":\"USERID_ALT\",\"type\":\"string\"},{\"name\":\"DH_ALT\",\"type\":\"string\"}" +
				",{\"name\":\"SIBS_PEDIDO\",\"type\":\"string\"},{\"name\":\"SIBS_RESPOSTA\",\"type\":\"string\"}" +
				",{\"name\":\"MEIO_PAGAMENTO\",\"type\":\"string\"},{\"name\":\"PAN_CARTAO\",\"type\":\"int\"},{\"" +
				"name\":\"FATURA_SIMPLIF\",\"type\":\"string\"},{\"name\":\"RODAPE_FAT_SIMP\",\"type\":\"string" +
				"\"},{\"name\":\"COD_JANELA\",\"type\":\"string\"}]}");
		private int _IDMSGBAN_1;
		private int _IDMSGBAN_2;
		private int _CONTA_CLI;
		private string _CODMSG_BS;
		private int _VERMSG;
		private int _DHMSG;
		private int _CODRESPS;
		private int _DT_RECOLHA;
		private string _ESTADO_ANT;
		private string _ESTADO_ACT;
		private int _RETURN_CODE;
		private string _RETURN_MSG;
		private int _TIPO_PEDIDO;
		private int _TIP_PAG_SER;
		private string _NIB_ORD;
		private int _ENTIDADE;
		private int _REFERENCIA;
		private int _REF_ESP;
		private int _REF_ADICIONAL;
		private int _REF_RESPOSTA;
		private string _MONTANTE;
		private string _REDE_ORIGEM;
		private string _CANAL_ORIGEM;
		private string _USERID_CLI;
		private string _CAT_NR;
		private string _CAT_CARTAO;
		private string _LOCMORTER;
		private string _CHAVE_TRF;
		private string _APLIC_N;
		private int _ID_LOG_SIBS;
		private int _NR_LOG_SIBS;
		private int _NR_CONTRIBUINTE;
		private int _NR_FACTURA;
		private string _DESCENT;
		private int _TIPSER;
		private string _CODMOEDA;
		private string _CODRECS;
		private string _RESP1;
		private string _RESP2;
		private int _BANCO_CLI;
		private int _BALCAO_CLI;
		private int _CKD_CLI;
		private string _DH_INS;
		private string _CONFIRMACAO_SIBS;
		private string _DH_CONFIRMACAO;
		private string _USERID_ALT;
		private string _DH_ALT;
		private string _SIBS_PEDIDO;
		private string _SIBS_RESPOSTA;
		private string _MEIO_PAGAMENTO;
		private int _PAN_CARTAO;
		private string _FATURA_SIMPLIF;
		private string _RODAPE_FAT_SIMP;
		private string _COD_JANELA;
		public virtual Schema Schema
		{
			get
			{
				return AfterImageH2h._SCHEMA;
			}
		}
		public int IDMSGBAN_1
		{
			get
			{
				return this._IDMSGBAN_1;
			}
			set
			{
				this._IDMSGBAN_1 = value;
			}
		}
		public int IDMSGBAN_2
		{
			get
			{
				return this._IDMSGBAN_2;
			}
			set
			{
				this._IDMSGBAN_2 = value;
			}
		}
		public int CONTA_CLI
		{
			get
			{
				return this._CONTA_CLI;
			}
			set
			{
				this._CONTA_CLI = value;
			}
		}
		public string CODMSG_BS
		{
			get
			{
				return this._CODMSG_BS;
			}
			set
			{
				this._CODMSG_BS = value;
			}
		}
		public int VERMSG
		{
			get
			{
				return this._VERMSG;
			}
			set
			{
				this._VERMSG = value;
			}
		}
		public int DHMSG
		{
			get
			{
				return this._DHMSG;
			}
			set
			{
				this._DHMSG = value;
			}
		}
		public int CODRESPS
		{
			get
			{
				return this._CODRESPS;
			}
			set
			{
				this._CODRESPS = value;
			}
		}
		public int DT_RECOLHA
		{
			get
			{
				return this._DT_RECOLHA;
			}
			set
			{
				this._DT_RECOLHA = value;
			}
		}
		public string ESTADO_ANT
		{
			get
			{
				return this._ESTADO_ANT;
			}
			set
			{
				this._ESTADO_ANT = value;
			}
		}
		public string ESTADO_ACT
		{
			get
			{
				return this._ESTADO_ACT;
			}
			set
			{
				this._ESTADO_ACT = value;
			}
		}
		public int RETURN_CODE
		{
			get
			{
				return this._RETURN_CODE;
			}
			set
			{
				this._RETURN_CODE = value;
			}
		}
		public string RETURN_MSG
		{
			get
			{
				return this._RETURN_MSG;
			}
			set
			{
				this._RETURN_MSG = value;
			}
		}
		public int TIPO_PEDIDO
		{
			get
			{
				return this._TIPO_PEDIDO;
			}
			set
			{
				this._TIPO_PEDIDO = value;
			}
		}
		public int TIP_PAG_SER
		{
			get
			{
				return this._TIP_PAG_SER;
			}
			set
			{
				this._TIP_PAG_SER = value;
			}
		}
		public string NIB_ORD
		{
			get
			{
				return this._NIB_ORD;
			}
			set
			{
				this._NIB_ORD = value;
			}
		}
		public int ENTIDADE
		{
			get
			{
				return this._ENTIDADE;
			}
			set
			{
				this._ENTIDADE = value;
			}
		}
		public int REFERENCIA
		{
			get
			{
				return this._REFERENCIA;
			}
			set
			{
				this._REFERENCIA = value;
			}
		}
		public int REF_ESP
		{
			get
			{
				return this._REF_ESP;
			}
			set
			{
				this._REF_ESP = value;
			}
		}
		public int REF_ADICIONAL
		{
			get
			{
				return this._REF_ADICIONAL;
			}
			set
			{
				this._REF_ADICIONAL = value;
			}
		}
		public int REF_RESPOSTA
		{
			get
			{
				return this._REF_RESPOSTA;
			}
			set
			{
				this._REF_RESPOSTA = value;
			}
		}
		public string MONTANTE
		{
			get
			{
				return this._MONTANTE;
			}
			set
			{
				this._MONTANTE = value;
			}
		}
		public string REDE_ORIGEM
		{
			get
			{
				return this._REDE_ORIGEM;
			}
			set
			{
				this._REDE_ORIGEM = value;
			}
		}
		public string CANAL_ORIGEM
		{
			get
			{
				return this._CANAL_ORIGEM;
			}
			set
			{
				this._CANAL_ORIGEM = value;
			}
		}
		public string USERID_CLI
		{
			get
			{
				return this._USERID_CLI;
			}
			set
			{
				this._USERID_CLI = value;
			}
		}
		public string CAT_NR
		{
			get
			{
				return this._CAT_NR;
			}
			set
			{
				this._CAT_NR = value;
			}
		}
		public string CAT_CARTAO
		{
			get
			{
				return this._CAT_CARTAO;
			}
			set
			{
				this._CAT_CARTAO = value;
			}
		}
		public string LOCMORTER
		{
			get
			{
				return this._LOCMORTER;
			}
			set
			{
				this._LOCMORTER = value;
			}
		}
		public string CHAVE_TRF
		{
			get
			{
				return this._CHAVE_TRF;
			}
			set
			{
				this._CHAVE_TRF = value;
			}
		}
		public string APLIC_N
		{
			get
			{
				return this._APLIC_N;
			}
			set
			{
				this._APLIC_N = value;
			}
		}
		public int ID_LOG_SIBS
		{
			get
			{
				return this._ID_LOG_SIBS;
			}
			set
			{
				this._ID_LOG_SIBS = value;
			}
		}
		public int NR_LOG_SIBS
		{
			get
			{
				return this._NR_LOG_SIBS;
			}
			set
			{
				this._NR_LOG_SIBS = value;
			}
		}
		public int NR_CONTRIBUINTE
		{
			get
			{
				return this._NR_CONTRIBUINTE;
			}
			set
			{
				this._NR_CONTRIBUINTE = value;
			}
		}
		public int NR_FACTURA
		{
			get
			{
				return this._NR_FACTURA;
			}
			set
			{
				this._NR_FACTURA = value;
			}
		}
		public string DESCENT
		{
			get
			{
				return this._DESCENT;
			}
			set
			{
				this._DESCENT = value;
			}
		}
		public int TIPSER
		{
			get
			{
				return this._TIPSER;
			}
			set
			{
				this._TIPSER = value;
			}
		}
		public string CODMOEDA
		{
			get
			{
				return this._CODMOEDA;
			}
			set
			{
				this._CODMOEDA = value;
			}
		}
		public string CODRECS
		{
			get
			{
				return this._CODRECS;
			}
			set
			{
				this._CODRECS = value;
			}
		}
		public string RESP1
		{
			get
			{
				return this._RESP1;
			}
			set
			{
				this._RESP1 = value;
			}
		}
		public string RESP2
		{
			get
			{
				return this._RESP2;
			}
			set
			{
				this._RESP2 = value;
			}
		}
		public int BANCO_CLI
		{
			get
			{
				return this._BANCO_CLI;
			}
			set
			{
				this._BANCO_CLI = value;
			}
		}
		public int BALCAO_CLI
		{
			get
			{
				return this._BALCAO_CLI;
			}
			set
			{
				this._BALCAO_CLI = value;
			}
		}
		public int CKD_CLI
		{
			get
			{
				return this._CKD_CLI;
			}
			set
			{
				this._CKD_CLI = value;
			}
		}
		public string DH_INS
		{
			get
			{
				return this._DH_INS;
			}
			set
			{
				this._DH_INS = value;
			}
		}
		public string CONFIRMACAO_SIBS
		{
			get
			{
				return this._CONFIRMACAO_SIBS;
			}
			set
			{
				this._CONFIRMACAO_SIBS = value;
			}
		}
		public string DH_CONFIRMACAO
		{
			get
			{
				return this._DH_CONFIRMACAO;
			}
			set
			{
				this._DH_CONFIRMACAO = value;
			}
		}
		public string USERID_ALT
		{
			get
			{
				return this._USERID_ALT;
			}
			set
			{
				this._USERID_ALT = value;
			}
		}
		public string DH_ALT
		{
			get
			{
				return this._DH_ALT;
			}
			set
			{
				this._DH_ALT = value;
			}
		}
		public string SIBS_PEDIDO
		{
			get
			{
				return this._SIBS_PEDIDO;
			}
			set
			{
				this._SIBS_PEDIDO = value;
			}
		}
		public string SIBS_RESPOSTA
		{
			get
			{
				return this._SIBS_RESPOSTA;
			}
			set
			{
				this._SIBS_RESPOSTA = value;
			}
		}
		public string MEIO_PAGAMENTO
		{
			get
			{
				return this._MEIO_PAGAMENTO;
			}
			set
			{
				this._MEIO_PAGAMENTO = value;
			}
		}
		public int PAN_CARTAO
		{
			get
			{
				return this._PAN_CARTAO;
			}
			set
			{
				this._PAN_CARTAO = value;
			}
		}
		public string FATURA_SIMPLIF
		{
			get
			{
				return this._FATURA_SIMPLIF;
			}
			set
			{
				this._FATURA_SIMPLIF = value;
			}
		}
		public string RODAPE_FAT_SIMP
		{
			get
			{
				return this._RODAPE_FAT_SIMP;
			}
			set
			{
				this._RODAPE_FAT_SIMP = value;
			}
		}
		public string COD_JANELA
		{
			get
			{
				return this._COD_JANELA;
			}
			set
			{
				this._COD_JANELA = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.IDMSGBAN_1;
			case 1: return this.IDMSGBAN_2;
			case 2: return this.CONTA_CLI;
			case 3: return this.CODMSG_BS;
			case 4: return this.VERMSG;
			case 5: return this.DHMSG;
			case 6: return this.CODRESPS;
			case 7: return this.DT_RECOLHA;
			case 8: return this.ESTADO_ANT;
			case 9: return this.ESTADO_ACT;
			case 10: return this.RETURN_CODE;
			case 11: return this.RETURN_MSG;
			case 12: return this.TIPO_PEDIDO;
			case 13: return this.TIP_PAG_SER;
			case 14: return this.NIB_ORD;
			case 15: return this.ENTIDADE;
			case 16: return this.REFERENCIA;
			case 17: return this.REF_ESP;
			case 18: return this.REF_ADICIONAL;
			case 19: return this.REF_RESPOSTA;
			case 20: return this.MONTANTE;
			case 21: return this.REDE_ORIGEM;
			case 22: return this.CANAL_ORIGEM;
			case 23: return this.USERID_CLI;
			case 24: return this.CAT_NR;
			case 25: return this.CAT_CARTAO;
			case 26: return this.LOCMORTER;
			case 27: return this.CHAVE_TRF;
			case 28: return this.APLIC_N;
			case 29: return this.ID_LOG_SIBS;
			case 30: return this.NR_LOG_SIBS;
			case 31: return this.NR_CONTRIBUINTE;
			case 32: return this.NR_FACTURA;
			case 33: return this.DESCENT;
			case 34: return this.TIPSER;
			case 35: return this.CODMOEDA;
			case 36: return this.CODRECS;
			case 37: return this.RESP1;
			case 38: return this.RESP2;
			case 39: return this.BANCO_CLI;
			case 40: return this.BALCAO_CLI;
			case 41: return this.CKD_CLI;
			case 42: return this.DH_INS;
			case 43: return this.CONFIRMACAO_SIBS;
			case 44: return this.DH_CONFIRMACAO;
			case 45: return this.USERID_ALT;
			case 46: return this.DH_ALT;
			case 47: return this.SIBS_PEDIDO;
			case 48: return this.SIBS_RESPOSTA;
			case 49: return this.MEIO_PAGAMENTO;
			case 50: return this.PAN_CARTAO;
			case 51: return this.FATURA_SIMPLIF;
			case 52: return this.RODAPE_FAT_SIMP;
			case 53: return this.COD_JANELA;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.IDMSGBAN_1 = (System.Int32)fieldValue; break;
			case 1: this.IDMSGBAN_2 = (System.Int32)fieldValue; break;
			case 2: this.CONTA_CLI = (System.Int32)fieldValue; break;
			case 3: this.CODMSG_BS = (System.String)fieldValue; break;
			case 4: this.VERMSG = (System.Int32)fieldValue; break;
			case 5: this.DHMSG = (System.Int32)fieldValue; break;
			case 6: this.CODRESPS = (System.Int32)fieldValue; break;
			case 7: this.DT_RECOLHA = (System.Int32)fieldValue; break;
			case 8: this.ESTADO_ANT = (System.String)fieldValue; break;
			case 9: this.ESTADO_ACT = (System.String)fieldValue; break;
			case 10: this.RETURN_CODE = (System.Int32)fieldValue; break;
			case 11: this.RETURN_MSG = (System.String)fieldValue; break;
			case 12: this.TIPO_PEDIDO = (System.Int32)fieldValue; break;
			case 13: this.TIP_PAG_SER = (System.Int32)fieldValue; break;
			case 14: this.NIB_ORD = (System.String)fieldValue; break;
			case 15: this.ENTIDADE = (System.Int32)fieldValue; break;
			case 16: this.REFERENCIA = (System.Int32)fieldValue; break;
			case 17: this.REF_ESP = (System.Int32)fieldValue; break;
			case 18: this.REF_ADICIONAL = (System.Int32)fieldValue; break;
			case 19: this.REF_RESPOSTA = (System.Int32)fieldValue; break;
			case 20: this.MONTANTE = (System.String)fieldValue; break;
			case 21: this.REDE_ORIGEM = (System.String)fieldValue; break;
			case 22: this.CANAL_ORIGEM = (System.String)fieldValue; break;
			case 23: this.USERID_CLI = (System.String)fieldValue; break;
			case 24: this.CAT_NR = (System.String)fieldValue; break;
			case 25: this.CAT_CARTAO = (System.String)fieldValue; break;
			case 26: this.LOCMORTER = (System.String)fieldValue; break;
			case 27: this.CHAVE_TRF = (System.String)fieldValue; break;
			case 28: this.APLIC_N = (System.String)fieldValue; break;
			case 29: this.ID_LOG_SIBS = (System.Int32)fieldValue; break;
			case 30: this.NR_LOG_SIBS = (System.Int32)fieldValue; break;
			case 31: this.NR_CONTRIBUINTE = (System.Int32)fieldValue; break;
			case 32: this.NR_FACTURA = (System.Int32)fieldValue; break;
			case 33: this.DESCENT = (System.String)fieldValue; break;
			case 34: this.TIPSER = (System.Int32)fieldValue; break;
			case 35: this.CODMOEDA = (System.String)fieldValue; break;
			case 36: this.CODRECS = (System.String)fieldValue; break;
			case 37: this.RESP1 = (System.String)fieldValue; break;
			case 38: this.RESP2 = (System.String)fieldValue; break;
			case 39: this.BANCO_CLI = (System.Int32)fieldValue; break;
			case 40: this.BALCAO_CLI = (System.Int32)fieldValue; break;
			case 41: this.CKD_CLI = (System.Int32)fieldValue; break;
			case 42: this.DH_INS = (System.String)fieldValue; break;
			case 43: this.CONFIRMACAO_SIBS = (System.String)fieldValue; break;
			case 44: this.DH_CONFIRMACAO = (System.String)fieldValue; break;
			case 45: this.USERID_ALT = (System.String)fieldValue; break;
			case 46: this.DH_ALT = (System.String)fieldValue; break;
			case 47: this.SIBS_PEDIDO = (System.String)fieldValue; break;
			case 48: this.SIBS_RESPOSTA = (System.String)fieldValue; break;
			case 49: this.MEIO_PAGAMENTO = (System.String)fieldValue; break;
			case 50: this.PAN_CARTAO = (System.Int32)fieldValue; break;
			case 51: this.FATURA_SIMPLIF = (System.String)fieldValue; break;
			case 52: this.RODAPE_FAT_SIMP = (System.String)fieldValue; break;
			case 53: this.COD_JANELA = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
