// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EdpSimulator.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class AfterImageCards : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"AfterImageCards\",\"namespace\":\"EdpSimulator.Entities\",\"fields\":[{\"name" +
				"\":\"TXN_DT\",\"type\":\"string\"},{\"name\":\"TXN_TM\",\"type\":\"int\"},{\"name\":\"TXN_AMT\",\"ty" +
				"pe\":\"string\"},{\"name\":\"TXN_SINAL\",\"type\":\"string\"},{\"name\":\"ORIG_PLAS\",\"type\":\"s" +
				"tring\"},{\"name\":\"ACCT_COID\",\"type\":\"int\"},{\"name\":\"ACCT_PROD\",\"type\":\"string\"},{" +
				"\"name\":\"ACCT_NBR\",\"type\":\"string\"},{\"name\":\"FILE_ORIG\",\"type\":\"string\"},{\"name\":" +
				"\"PSTG_DT\",\"type\":\"int\"},{\"name\":\"PSTG_SEQ\",\"type\":\"int\"},{\"name\":\"TIPO_CRT\",\"typ" +
				"e\":\"string\"},{\"name\":\"TXN_FMT_IND\",\"type\":\"string\"},{\"name\":\"TXN_SRCE\",\"type\":\"s" +
				"tring\"},{\"name\":\"TXN_CATG\",\"type\":\"string\"},{\"name\":\"TXN_3RD_LVL\",\"type\":\"string" +
				"\"},{\"name\":\"TXN_4TH_LVL\",\"type\":\"string\"},{\"name\":\"TXN_5TH_LVL\",\"type\":\"string\"}" +
				",{\"name\":\"PRT_ON_STMT\",\"type\":\"string\"},{\"name\":\"TXN_CD\",\"type\":\"int\"},{\"name\":\"" +
				"TXN_DESC\",\"type\":\"string\"},{\"name\":\"TXN_CNTRY_CD\",\"type\":\"string\"},{\"name\":\"TXN_" +
				"FGN_CUR_CD\",\"type\":\"string\"},{\"name\":\"TXN_FGN_AMT\",\"type\":\"string\"},{\"name\":\"TXN" +
				"_FGN_TC\",\"type\":\"string\"},{\"name\":\"TXN_OPER\",\"type\":\"string\"},{\"name\":\"TXN_MCC\"," +
				"\"type\":\"string\"},{\"name\":\"TXN_TERM_ID\",\"type\":\"string\"},{\"name\":\"TIPO_OPER\",\"typ" +
				"e\":\"string\"},{\"name\":\"TIPO_TERM\",\"type\":\"string\"},{\"name\":\"TIPO_AUTH_CLI\",\"type\"" +
				":\"string\"},{\"name\":\"TIPO_AUTH_CRT\",\"type\":\"string\"},{\"name\":\"MRCH_DESC\",\"type\":\"" +
				"string\"},{\"name\":\"NAT_OPER\",\"type\":\"int\"},{\"name\":\"TOKEN_LVL\",\"type\":\"string\"},{" +
				"\"name\":\"WALTIP\",\"type\":\"string\"},{\"name\":\"APLIC_TXN\",\"type\":\"string\"},{\"name\":\"A" +
				"VAIL_CR_LN\",\"type\":\"string\"},{\"name\":\"EMB_NM_LN_1\",\"type\":\"string\"},{\"name\":\"PLA" +
				"S_TENANT\",\"type\":\"string\"},{\"name\":\"NUM_CIS\",\"type\":\"int\"},{\"name\":\"ACCT_FIID\",\"" +
				"type\":\"string\"},{\"name\":\"ACCT_TYP_CD\",\"type\":\"string\"},{\"name\":\"CTL_ACCT_IND\",\"t" +
				"ype\":\"string\"},{\"name\":\"ACCT_CUR_CD\",\"type\":\"string\"},{\"name\":\"OFF\",\"type\":\"stri" +
				"ng\"},{\"name\":\"CTL_ACCT_COID\",\"type\":\"int\"},{\"name\":\"CTL_ACCT_PROD\",\"type\":\"strin" +
				"g\"},{\"name\":\"CTL_ACCT_NBR\",\"type\":\"string\"},{\"name\":\"TIPO_MIG\",\"type\":\"string\"}," +
				"{\"name\":\"RA_IBAN\",\"type\":\"string\"},{\"name\":\"BANCO\",\"type\":\"string\"},{\"name\":\"REF" +
				"_SIST_ORIG\",\"type\":\"string\"},{\"name\":\"IBAN_ORDEN\",\"type\":\"string\"},{\"name\":\"NOME" +
				"_ORDEN\",\"type\":\"string\"},{\"name\":\"IBAN_DEST\",\"type\":\"string\"},{\"name\":\"NOME_DEST" +
				"\",\"type\":\"string\"},{\"name\":\"ENTIDADE\",\"type\":\"int\"},{\"name\":\"REFERENCIA\",\"type\":" +
				"\"int\"},{\"name\":\"REF_PAG_ESTADO\",\"type\":\"int\"},{\"name\":\"USER_INS\",\"type\":\"string\"" +
				"},{\"name\":\"TIMESTAMP_INS\",\"type\":\"string\"},{\"name\":\"USER_ALT\",\"type\":\"string\"},{" +
				"\"name\":\"TIMESTAMP_ALT\",\"type\":\"string\"},{\"name\":\"LOG_ACCAO\",\"type\":\"string\"},{\"n" +
				"ame\":\"ODS_PSTG_DT\",\"type\":\"int\"},{\"name\":\"ODS_PSTG_SEQ\",\"type\":\"int\"},{\"name\":\"C" +
				"AM_AU_PSTG_DT\",\"type\":\"int\"},{\"name\":\"CAM_AU_PSTG_SEQ\",\"type\":\"int\"},{\"name\":\"CA" +
				"M_PSTG_DT\",\"type\":\"int\"},{\"name\":\"CAM_PSTG_SEQ\",\"type\":\"int\"},{\"name\":\"SEQ_ID\",\"" +
				"type\":\"int\"}]}");
		private string _TXN_DT;
		private int _TXN_TM;
		private string _TXN_AMT;
		private string _TXN_SINAL;
		private string _ORIG_PLAS;
		private int _ACCT_COID;
		private string _ACCT_PROD;
		private string _ACCT_NBR;
		private string _FILE_ORIG;
		private int _PSTG_DT;
		private int _PSTG_SEQ;
		private string _TIPO_CRT;
		private string _TXN_FMT_IND;
		private string _TXN_SRCE;
		private string _TXN_CATG;
		private string _TXN_3RD_LVL;
		private string _TXN_4TH_LVL;
		private string _TXN_5TH_LVL;
		private string _PRT_ON_STMT;
		private int _TXN_CD;
		private string _TXN_DESC;
		private string _TXN_CNTRY_CD;
		private string _TXN_FGN_CUR_CD;
		private string _TXN_FGN_AMT;
		private string _TXN_FGN_TC;
		private string _TXN_OPER;
		private string _TXN_MCC;
		private string _TXN_TERM_ID;
		private string _TIPO_OPER;
		private string _TIPO_TERM;
		private string _TIPO_AUTH_CLI;
		private string _TIPO_AUTH_CRT;
		private string _MRCH_DESC;
		private int _NAT_OPER;
		private string _TOKEN_LVL;
		private string _WALTIP;
		private string _APLIC_TXN;
		private string _AVAIL_CR_LN;
		private string _EMB_NM_LN_1;
		private string _PLAS_TENANT;
		private int _NUM_CIS;
		private string _ACCT_FIID;
		private string _ACCT_TYP_CD;
		private string _CTL_ACCT_IND;
		private string _ACCT_CUR_CD;
		private string _OFF;
		private int _CTL_ACCT_COID;
		private string _CTL_ACCT_PROD;
		private string _CTL_ACCT_NBR;
		private string _TIPO_MIG;
		private string _RA_IBAN;
		private string _BANCO;
		private string _REF_SIST_ORIG;
		private string _IBAN_ORDEN;
		private string _NOME_ORDEN;
		private string _IBAN_DEST;
		private string _NOME_DEST;
		private int _ENTIDADE;
		private int _REFERENCIA;
		private int _REF_PAG_ESTADO;
		private string _USER_INS;
		private string _TIMESTAMP_INS;
		private string _USER_ALT;
		private string _TIMESTAMP_ALT;
		private string _LOG_ACCAO;
		private int _ODS_PSTG_DT;
		private int _ODS_PSTG_SEQ;
		private int _CAM_AU_PSTG_DT;
		private int _CAM_AU_PSTG_SEQ;
		private int _CAM_PSTG_DT;
		private int _CAM_PSTG_SEQ;
		private int _SEQ_ID;
		public virtual Schema Schema
		{
			get
			{
				return AfterImageCards._SCHEMA;
			}
		}
		public string TXN_DT
		{
			get
			{
				return this._TXN_DT;
			}
			set
			{
				this._TXN_DT = value;
			}
		}
		public int TXN_TM
		{
			get
			{
				return this._TXN_TM;
			}
			set
			{
				this._TXN_TM = value;
			}
		}
		public string TXN_AMT
		{
			get
			{
				return this._TXN_AMT;
			}
			set
			{
				this._TXN_AMT = value;
			}
		}
		public string TXN_SINAL
		{
			get
			{
				return this._TXN_SINAL;
			}
			set
			{
				this._TXN_SINAL = value;
			}
		}
		public string ORIG_PLAS
		{
			get
			{
				return this._ORIG_PLAS;
			}
			set
			{
				this._ORIG_PLAS = value;
			}
		}
		public int ACCT_COID
		{
			get
			{
				return this._ACCT_COID;
			}
			set
			{
				this._ACCT_COID = value;
			}
		}
		public string ACCT_PROD
		{
			get
			{
				return this._ACCT_PROD;
			}
			set
			{
				this._ACCT_PROD = value;
			}
		}
		public string ACCT_NBR
		{
			get
			{
				return this._ACCT_NBR;
			}
			set
			{
				this._ACCT_NBR = value;
			}
		}
		public string FILE_ORIG
		{
			get
			{
				return this._FILE_ORIG;
			}
			set
			{
				this._FILE_ORIG = value;
			}
		}
		public int PSTG_DT
		{
			get
			{
				return this._PSTG_DT;
			}
			set
			{
				this._PSTG_DT = value;
			}
		}
		public int PSTG_SEQ
		{
			get
			{
				return this._PSTG_SEQ;
			}
			set
			{
				this._PSTG_SEQ = value;
			}
		}
		public string TIPO_CRT
		{
			get
			{
				return this._TIPO_CRT;
			}
			set
			{
				this._TIPO_CRT = value;
			}
		}
		public string TXN_FMT_IND
		{
			get
			{
				return this._TXN_FMT_IND;
			}
			set
			{
				this._TXN_FMT_IND = value;
			}
		}
		public string TXN_SRCE
		{
			get
			{
				return this._TXN_SRCE;
			}
			set
			{
				this._TXN_SRCE = value;
			}
		}
		public string TXN_CATG
		{
			get
			{
				return this._TXN_CATG;
			}
			set
			{
				this._TXN_CATG = value;
			}
		}
		public string TXN_3RD_LVL
		{
			get
			{
				return this._TXN_3RD_LVL;
			}
			set
			{
				this._TXN_3RD_LVL = value;
			}
		}
		public string TXN_4TH_LVL
		{
			get
			{
				return this._TXN_4TH_LVL;
			}
			set
			{
				this._TXN_4TH_LVL = value;
			}
		}
		public string TXN_5TH_LVL
		{
			get
			{
				return this._TXN_5TH_LVL;
			}
			set
			{
				this._TXN_5TH_LVL = value;
			}
		}
		public string PRT_ON_STMT
		{
			get
			{
				return this._PRT_ON_STMT;
			}
			set
			{
				this._PRT_ON_STMT = value;
			}
		}
		public int TXN_CD
		{
			get
			{
				return this._TXN_CD;
			}
			set
			{
				this._TXN_CD = value;
			}
		}
		public string TXN_DESC
		{
			get
			{
				return this._TXN_DESC;
			}
			set
			{
				this._TXN_DESC = value;
			}
		}
		public string TXN_CNTRY_CD
		{
			get
			{
				return this._TXN_CNTRY_CD;
			}
			set
			{
				this._TXN_CNTRY_CD = value;
			}
		}
		public string TXN_FGN_CUR_CD
		{
			get
			{
				return this._TXN_FGN_CUR_CD;
			}
			set
			{
				this._TXN_FGN_CUR_CD = value;
			}
		}
		public string TXN_FGN_AMT
		{
			get
			{
				return this._TXN_FGN_AMT;
			}
			set
			{
				this._TXN_FGN_AMT = value;
			}
		}
		public string TXN_FGN_TC
		{
			get
			{
				return this._TXN_FGN_TC;
			}
			set
			{
				this._TXN_FGN_TC = value;
			}
		}
		public string TXN_OPER
		{
			get
			{
				return this._TXN_OPER;
			}
			set
			{
				this._TXN_OPER = value;
			}
		}
		public string TXN_MCC
		{
			get
			{
				return this._TXN_MCC;
			}
			set
			{
				this._TXN_MCC = value;
			}
		}
		public string TXN_TERM_ID
		{
			get
			{
				return this._TXN_TERM_ID;
			}
			set
			{
				this._TXN_TERM_ID = value;
			}
		}
		public string TIPO_OPER
		{
			get
			{
				return this._TIPO_OPER;
			}
			set
			{
				this._TIPO_OPER = value;
			}
		}
		public string TIPO_TERM
		{
			get
			{
				return this._TIPO_TERM;
			}
			set
			{
				this._TIPO_TERM = value;
			}
		}
		public string TIPO_AUTH_CLI
		{
			get
			{
				return this._TIPO_AUTH_CLI;
			}
			set
			{
				this._TIPO_AUTH_CLI = value;
			}
		}
		public string TIPO_AUTH_CRT
		{
			get
			{
				return this._TIPO_AUTH_CRT;
			}
			set
			{
				this._TIPO_AUTH_CRT = value;
			}
		}
		public string MRCH_DESC
		{
			get
			{
				return this._MRCH_DESC;
			}
			set
			{
				this._MRCH_DESC = value;
			}
		}
		public int NAT_OPER
		{
			get
			{
				return this._NAT_OPER;
			}
			set
			{
				this._NAT_OPER = value;
			}
		}
		public string TOKEN_LVL
		{
			get
			{
				return this._TOKEN_LVL;
			}
			set
			{
				this._TOKEN_LVL = value;
			}
		}
		public string WALTIP
		{
			get
			{
				return this._WALTIP;
			}
			set
			{
				this._WALTIP = value;
			}
		}
		public string APLIC_TXN
		{
			get
			{
				return this._APLIC_TXN;
			}
			set
			{
				this._APLIC_TXN = value;
			}
		}
		public string AVAIL_CR_LN
		{
			get
			{
				return this._AVAIL_CR_LN;
			}
			set
			{
				this._AVAIL_CR_LN = value;
			}
		}
		public string EMB_NM_LN_1
		{
			get
			{
				return this._EMB_NM_LN_1;
			}
			set
			{
				this._EMB_NM_LN_1 = value;
			}
		}
		public string PLAS_TENANT
		{
			get
			{
				return this._PLAS_TENANT;
			}
			set
			{
				this._PLAS_TENANT = value;
			}
		}
		public int NUM_CIS
		{
			get
			{
				return this._NUM_CIS;
			}
			set
			{
				this._NUM_CIS = value;
			}
		}
		public string ACCT_FIID
		{
			get
			{
				return this._ACCT_FIID;
			}
			set
			{
				this._ACCT_FIID = value;
			}
		}
		public string ACCT_TYP_CD
		{
			get
			{
				return this._ACCT_TYP_CD;
			}
			set
			{
				this._ACCT_TYP_CD = value;
			}
		}
		public string CTL_ACCT_IND
		{
			get
			{
				return this._CTL_ACCT_IND;
			}
			set
			{
				this._CTL_ACCT_IND = value;
			}
		}
		public string ACCT_CUR_CD
		{
			get
			{
				return this._ACCT_CUR_CD;
			}
			set
			{
				this._ACCT_CUR_CD = value;
			}
		}
		public string OFF
		{
			get
			{
				return this._OFF;
			}
			set
			{
				this._OFF = value;
			}
		}
		public int CTL_ACCT_COID
		{
			get
			{
				return this._CTL_ACCT_COID;
			}
			set
			{
				this._CTL_ACCT_COID = value;
			}
		}
		public string CTL_ACCT_PROD
		{
			get
			{
				return this._CTL_ACCT_PROD;
			}
			set
			{
				this._CTL_ACCT_PROD = value;
			}
		}
		public string CTL_ACCT_NBR
		{
			get
			{
				return this._CTL_ACCT_NBR;
			}
			set
			{
				this._CTL_ACCT_NBR = value;
			}
		}
		public string TIPO_MIG
		{
			get
			{
				return this._TIPO_MIG;
			}
			set
			{
				this._TIPO_MIG = value;
			}
		}
		public string RA_IBAN
		{
			get
			{
				return this._RA_IBAN;
			}
			set
			{
				this._RA_IBAN = value;
			}
		}
		public string BANCO
		{
			get
			{
				return this._BANCO;
			}
			set
			{
				this._BANCO = value;
			}
		}
		public string REF_SIST_ORIG
		{
			get
			{
				return this._REF_SIST_ORIG;
			}
			set
			{
				this._REF_SIST_ORIG = value;
			}
		}
		public string IBAN_ORDEN
		{
			get
			{
				return this._IBAN_ORDEN;
			}
			set
			{
				this._IBAN_ORDEN = value;
			}
		}
		public string NOME_ORDEN
		{
			get
			{
				return this._NOME_ORDEN;
			}
			set
			{
				this._NOME_ORDEN = value;
			}
		}
		public string IBAN_DEST
		{
			get
			{
				return this._IBAN_DEST;
			}
			set
			{
				this._IBAN_DEST = value;
			}
		}
		public string NOME_DEST
		{
			get
			{
				return this._NOME_DEST;
			}
			set
			{
				this._NOME_DEST = value;
			}
		}
		public int ENTIDADE
		{
			get
			{
				return this._ENTIDADE;
			}
			set
			{
				this._ENTIDADE = value;
			}
		}
		public int REFERENCIA
		{
			get
			{
				return this._REFERENCIA;
			}
			set
			{
				this._REFERENCIA = value;
			}
		}
		public int REF_PAG_ESTADO
		{
			get
			{
				return this._REF_PAG_ESTADO;
			}
			set
			{
				this._REF_PAG_ESTADO = value;
			}
		}
		public string USER_INS
		{
			get
			{
				return this._USER_INS;
			}
			set
			{
				this._USER_INS = value;
			}
		}
		public string TIMESTAMP_INS
		{
			get
			{
				return this._TIMESTAMP_INS;
			}
			set
			{
				this._TIMESTAMP_INS = value;
			}
		}
		public string USER_ALT
		{
			get
			{
				return this._USER_ALT;
			}
			set
			{
				this._USER_ALT = value;
			}
		}
		public string TIMESTAMP_ALT
		{
			get
			{
				return this._TIMESTAMP_ALT;
			}
			set
			{
				this._TIMESTAMP_ALT = value;
			}
		}
		public string LOG_ACCAO
		{
			get
			{
				return this._LOG_ACCAO;
			}
			set
			{
				this._LOG_ACCAO = value;
			}
		}
		public int ODS_PSTG_DT
		{
			get
			{
				return this._ODS_PSTG_DT;
			}
			set
			{
				this._ODS_PSTG_DT = value;
			}
		}
		public int ODS_PSTG_SEQ
		{
			get
			{
				return this._ODS_PSTG_SEQ;
			}
			set
			{
				this._ODS_PSTG_SEQ = value;
			}
		}
		public int CAM_AU_PSTG_DT
		{
			get
			{
				return this._CAM_AU_PSTG_DT;
			}
			set
			{
				this._CAM_AU_PSTG_DT = value;
			}
		}
		public int CAM_AU_PSTG_SEQ
		{
			get
			{
				return this._CAM_AU_PSTG_SEQ;
			}
			set
			{
				this._CAM_AU_PSTG_SEQ = value;
			}
		}
		public int CAM_PSTG_DT
		{
			get
			{
				return this._CAM_PSTG_DT;
			}
			set
			{
				this._CAM_PSTG_DT = value;
			}
		}
		public int CAM_PSTG_SEQ
		{
			get
			{
				return this._CAM_PSTG_SEQ;
			}
			set
			{
				this._CAM_PSTG_SEQ = value;
			}
		}
		public int SEQ_ID
		{
			get
			{
				return this._SEQ_ID;
			}
			set
			{
				this._SEQ_ID = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.TXN_DT;
			case 1: return this.TXN_TM;
			case 2: return this.TXN_AMT;
			case 3: return this.TXN_SINAL;
			case 4: return this.ORIG_PLAS;
			case 5: return this.ACCT_COID;
			case 6: return this.ACCT_PROD;
			case 7: return this.ACCT_NBR;
			case 8: return this.FILE_ORIG;
			case 9: return this.PSTG_DT;
			case 10: return this.PSTG_SEQ;
			case 11: return this.TIPO_CRT;
			case 12: return this.TXN_FMT_IND;
			case 13: return this.TXN_SRCE;
			case 14: return this.TXN_CATG;
			case 15: return this.TXN_3RD_LVL;
			case 16: return this.TXN_4TH_LVL;
			case 17: return this.TXN_5TH_LVL;
			case 18: return this.PRT_ON_STMT;
			case 19: return this.TXN_CD;
			case 20: return this.TXN_DESC;
			case 21: return this.TXN_CNTRY_CD;
			case 22: return this.TXN_FGN_CUR_CD;
			case 23: return this.TXN_FGN_AMT;
			case 24: return this.TXN_FGN_TC;
			case 25: return this.TXN_OPER;
			case 26: return this.TXN_MCC;
			case 27: return this.TXN_TERM_ID;
			case 28: return this.TIPO_OPER;
			case 29: return this.TIPO_TERM;
			case 30: return this.TIPO_AUTH_CLI;
			case 31: return this.TIPO_AUTH_CRT;
			case 32: return this.MRCH_DESC;
			case 33: return this.NAT_OPER;
			case 34: return this.TOKEN_LVL;
			case 35: return this.WALTIP;
			case 36: return this.APLIC_TXN;
			case 37: return this.AVAIL_CR_LN;
			case 38: return this.EMB_NM_LN_1;
			case 39: return this.PLAS_TENANT;
			case 40: return this.NUM_CIS;
			case 41: return this.ACCT_FIID;
			case 42: return this.ACCT_TYP_CD;
			case 43: return this.CTL_ACCT_IND;
			case 44: return this.ACCT_CUR_CD;
			case 45: return this.OFF;
			case 46: return this.CTL_ACCT_COID;
			case 47: return this.CTL_ACCT_PROD;
			case 48: return this.CTL_ACCT_NBR;
			case 49: return this.TIPO_MIG;
			case 50: return this.RA_IBAN;
			case 51: return this.BANCO;
			case 52: return this.REF_SIST_ORIG;
			case 53: return this.IBAN_ORDEN;
			case 54: return this.NOME_ORDEN;
			case 55: return this.IBAN_DEST;
			case 56: return this.NOME_DEST;
			case 57: return this.ENTIDADE;
			case 58: return this.REFERENCIA;
			case 59: return this.REF_PAG_ESTADO;
			case 60: return this.USER_INS;
			case 61: return this.TIMESTAMP_INS;
			case 62: return this.USER_ALT;
			case 63: return this.TIMESTAMP_ALT;
			case 64: return this.LOG_ACCAO;
			case 65: return this.ODS_PSTG_DT;
			case 66: return this.ODS_PSTG_SEQ;
			case 67: return this.CAM_AU_PSTG_DT;
			case 68: return this.CAM_AU_PSTG_SEQ;
			case 69: return this.CAM_PSTG_DT;
			case 70: return this.CAM_PSTG_SEQ;
			case 71: return this.SEQ_ID;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.TXN_DT = (System.String)fieldValue; break;
			case 1: this.TXN_TM = (System.Int32)fieldValue; break;
			case 2: this.TXN_AMT = (System.String)fieldValue; break;
			case 3: this.TXN_SINAL = (System.String)fieldValue; break;
			case 4: this.ORIG_PLAS = (System.String)fieldValue; break;
			case 5: this.ACCT_COID = (System.Int32)fieldValue; break;
			case 6: this.ACCT_PROD = (System.String)fieldValue; break;
			case 7: this.ACCT_NBR = (System.String)fieldValue; break;
			case 8: this.FILE_ORIG = (System.String)fieldValue; break;
			case 9: this.PSTG_DT = (System.Int32)fieldValue; break;
			case 10: this.PSTG_SEQ = (System.Int32)fieldValue; break;
			case 11: this.TIPO_CRT = (System.String)fieldValue; break;
			case 12: this.TXN_FMT_IND = (System.String)fieldValue; break;
			case 13: this.TXN_SRCE = (System.String)fieldValue; break;
			case 14: this.TXN_CATG = (System.String)fieldValue; break;
			case 15: this.TXN_3RD_LVL = (System.String)fieldValue; break;
			case 16: this.TXN_4TH_LVL = (System.String)fieldValue; break;
			case 17: this.TXN_5TH_LVL = (System.String)fieldValue; break;
			case 18: this.PRT_ON_STMT = (System.String)fieldValue; break;
			case 19: this.TXN_CD = (System.Int32)fieldValue; break;
			case 20: this.TXN_DESC = (System.String)fieldValue; break;
			case 21: this.TXN_CNTRY_CD = (System.String)fieldValue; break;
			case 22: this.TXN_FGN_CUR_CD = (System.String)fieldValue; break;
			case 23: this.TXN_FGN_AMT = (System.String)fieldValue; break;
			case 24: this.TXN_FGN_TC = (System.String)fieldValue; break;
			case 25: this.TXN_OPER = (System.String)fieldValue; break;
			case 26: this.TXN_MCC = (System.String)fieldValue; break;
			case 27: this.TXN_TERM_ID = (System.String)fieldValue; break;
			case 28: this.TIPO_OPER = (System.String)fieldValue; break;
			case 29: this.TIPO_TERM = (System.String)fieldValue; break;
			case 30: this.TIPO_AUTH_CLI = (System.String)fieldValue; break;
			case 31: this.TIPO_AUTH_CRT = (System.String)fieldValue; break;
			case 32: this.MRCH_DESC = (System.String)fieldValue; break;
			case 33: this.NAT_OPER = (System.Int32)fieldValue; break;
			case 34: this.TOKEN_LVL = (System.String)fieldValue; break;
			case 35: this.WALTIP = (System.String)fieldValue; break;
			case 36: this.APLIC_TXN = (System.String)fieldValue; break;
			case 37: this.AVAIL_CR_LN = (System.String)fieldValue; break;
			case 38: this.EMB_NM_LN_1 = (System.String)fieldValue; break;
			case 39: this.PLAS_TENANT = (System.String)fieldValue; break;
			case 40: this.NUM_CIS = (System.Int32)fieldValue; break;
			case 41: this.ACCT_FIID = (System.String)fieldValue; break;
			case 42: this.ACCT_TYP_CD = (System.String)fieldValue; break;
			case 43: this.CTL_ACCT_IND = (System.String)fieldValue; break;
			case 44: this.ACCT_CUR_CD = (System.String)fieldValue; break;
			case 45: this.OFF = (System.String)fieldValue; break;
			case 46: this.CTL_ACCT_COID = (System.Int32)fieldValue; break;
			case 47: this.CTL_ACCT_PROD = (System.String)fieldValue; break;
			case 48: this.CTL_ACCT_NBR = (System.String)fieldValue; break;
			case 49: this.TIPO_MIG = (System.String)fieldValue; break;
			case 50: this.RA_IBAN = (System.String)fieldValue; break;
			case 51: this.BANCO = (System.String)fieldValue; break;
			case 52: this.REF_SIST_ORIG = (System.String)fieldValue; break;
			case 53: this.IBAN_ORDEN = (System.String)fieldValue; break;
			case 54: this.NOME_ORDEN = (System.String)fieldValue; break;
			case 55: this.IBAN_DEST = (System.String)fieldValue; break;
			case 56: this.NOME_DEST = (System.String)fieldValue; break;
			case 57: this.ENTIDADE = (System.Int32)fieldValue; break;
			case 58: this.REFERENCIA = (System.Int32)fieldValue; break;
			case 59: this.REF_PAG_ESTADO = (System.Int32)fieldValue; break;
			case 60: this.USER_INS = (System.String)fieldValue; break;
			case 61: this.TIMESTAMP_INS = (System.String)fieldValue; break;
			case 62: this.USER_ALT = (System.String)fieldValue; break;
			case 63: this.TIMESTAMP_ALT = (System.String)fieldValue; break;
			case 64: this.LOG_ACCAO = (System.String)fieldValue; break;
			case 65: this.ODS_PSTG_DT = (System.Int32)fieldValue; break;
			case 66: this.ODS_PSTG_SEQ = (System.Int32)fieldValue; break;
			case 67: this.CAM_AU_PSTG_DT = (System.Int32)fieldValue; break;
			case 68: this.CAM_AU_PSTG_SEQ = (System.Int32)fieldValue; break;
			case 69: this.CAM_PSTG_DT = (System.Int32)fieldValue; break;
			case 70: this.CAM_PSTG_SEQ = (System.Int32)fieldValue; break;
			case 71: this.SEQ_ID = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
