// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EdpSimulator.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class JavaCardsRecord : IEdpRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"Cards\",\"namespace\":\"EdpSimulator.Entities\",\"fields\":[{\"name\":\"" +
				"afterImage\",\"type\":{\"type\":\"record\",\"name\":\"afterImage\",\"namespace\":\"EdpSimulator.Entities" +
				"ro\",\"fields\":[{\"name\":\"TXN_DT\",\"type\":\"string\"},{\"name\":\"TXN_TM\",\"type\":\"int\"},{" +
				"\"name\":\"TXN_AMT\",\"type\":\"string\"},{\"name\":\"TXN_SINAL\",\"type\":\"string\"},{\"name\":\"" +
				"ORIG_PLAS\",\"type\":\"string\"},{\"name\":\"ACCT_COID\",\"type\":\"int\"},{\"name\":\"ACCT_PROD" +
				"\",\"type\":\"string\"},{\"name\":\"ACCT_NBR\",\"type\":\"string\"},{\"name\":\"FILE_ORIG\",\"type" +
				"\":\"string\"},{\"name\":\"PSTG_DT\",\"type\":\"int\"},{\"name\":\"PSTG_SEQ\",\"type\":\"int\"},{\"n" +
				"ame\":\"TIPO_CRT\",\"type\":\"string\"},{\"name\":\"TXN_FMT_IND\",\"type\":\"string\"},{\"name\":" +
				"\"TXN_SRCE\",\"type\":\"string\"},{\"name\":\"TXN_CATG\",\"type\":\"string\"},{\"name\":\"TXN_3RD" +
				"_LVL\",\"type\":\"string\"},{\"name\":\"TXN_4TH_LVL\",\"type\":\"string\"},{\"name\":\"TXN_5TH_L" +
				"VL\",\"type\":\"string\"},{\"name\":\"PRT_ON_STMT\",\"type\":\"string\"},{\"name\":\"TXN_CD\",\"ty" +
				"pe\":\"int\"},{\"name\":\"TXN_DESC\",\"type\":\"string\"},{\"name\":\"TXN_CNTRY_CD\",\"type\":\"st" +
				"ring\"},{\"name\":\"TXN_FGN_CUR_CD\",\"type\":\"string\"},{\"name\":\"TXN_FGN_AMT\",\"type\":\"s" +
				"tring\"},{\"name\":\"TXN_FGN_TC\",\"type\":\"string\"},{\"name\":\"TXN_OPER\",\"type\":\"string\"" +
				"},{\"name\":\"TXN_MCC\",\"type\":\"string\"},{\"name\":\"TXN_TERM_ID\",\"type\":\"string\"},{\"na" +
				"me\":\"TIPO_OPER\",\"type\":\"string\"},{\"name\":\"TIPO_TERM\",\"type\":\"string\"},{\"name\":\"T" +
				"IPO_AUTH_CLI\",\"type\":\"string\"},{\"name\":\"TIPO_AUTH_CRT\",\"type\":\"string\"},{\"name\":" +
				"\"MRCH_DESC\",\"type\":\"string\"},{\"name\":\"NAT_OPER\",\"type\":\"int\"},{\"name\":\"TOKEN_LVL" +
				"\",\"type\":\"string\"},{\"name\":\"WALTIP\",\"type\":\"string\"},{\"name\":\"APLIC_TXN\",\"type\":" +
				"\"string\"},{\"name\":\"AVAIL_CR_LN\",\"type\":\"string\"},{\"name\":\"EMB_NM_LN_1\",\"type\":\"s" +
				"tring\"},{\"name\":\"PLAS_TENANT\",\"type\":\"string\"},{\"name\":\"NUM_CIS\",\"type\":\"int\"},{" +
				"\"name\":\"ACCT_FIID\",\"type\":\"string\"},{\"name\":\"ACCT_TYP_CD\",\"type\":\"string\"},{\"nam" +
				"e\":\"CTL_ACCT_IND\",\"type\":\"string\"},{\"name\":\"ACCT_CUR_CD\",\"type\":\"string\"},{\"name" +
				"\":\"OFF\",\"type\":\"string\"},{\"name\":\"CTL_ACCT_COID\",\"type\":\"int\"},{\"name\":\"CTL_ACCT" +
				"_PROD\",\"type\":\"string\"},{\"name\":\"CTL_ACCT_NBR\",\"type\":\"string\"},{\"name\":\"TIPO_MI" +
				"G\",\"type\":\"string\"},{\"name\":\"RA_IBAN\",\"type\":\"string\"},{\"name\":\"BANCO\",\"type\":\"s" +
				"tring\"},{\"name\":\"REF_SIST_ORIG\",\"type\":\"string\"},{\"name\":\"IBAN_ORDEN\",\"type\":\"st" +
				"ring\"},{\"name\":\"NOME_ORDEN\",\"type\":\"string\"},{\"name\":\"IBAN_DEST\",\"type\":\"string\"" +
				"},{\"name\":\"NOME_DEST\",\"type\":\"string\"},{\"name\":\"ENTIDADE\",\"type\":\"int\"},{\"name\":" +
				"\"REFERENCIA\",\"type\":\"int\"},{\"name\":\"REF_PAG_ESTADO\",\"type\":\"int\"},{\"name\":\"USER_" +
				"INS\",\"type\":\"string\"},{\"name\":\"TIMESTAMP_INS\",\"type\":\"string\"},{\"name\":\"USER_ALT" +
				"\",\"type\":\"string\"},{\"name\":\"TIMESTAMP_ALT\",\"type\":\"string\"},{\"name\":\"LOG_ACCAO\"," +
				"\"type\":\"string\"},{\"name\":\"ODS_PSTG_DT\",\"type\":\"int\"},{\"name\":\"ODS_PSTG_SEQ\",\"typ" +
				"e\":\"int\"},{\"name\":\"CAM_AU_PSTG_DT\",\"type\":\"int\"},{\"name\":\"CAM_AU_PSTG_SEQ\",\"type" +
				"\":\"int\"},{\"name\":\"CAM_PSTG_DT\",\"type\":\"int\"},{\"name\":\"CAM_PSTG_SEQ\",\"type\":\"int\"" +
				"},{\"name\":\"SEQ_ID\",\"type\":\"int\"}]}},{\"name\":\"beforeImage\",\"type\":[\"string\",\"null" +
				"\"]},{\"name\":\"A_ENTTYP\",\"type\":\"string\"},{\"name\":\"A_CCID\",\"type\":\"string\"},{\"name" +
				"\":\"A_TIMSTAMP\",\"type\":\"string\"}]}");
		private EdpSimulator.Entities.AfterImageCards _afterImage;
		private string _beforeImage;
		private string _A_ENTTYP;
		private string _A_CCID;
		private string _A_TIMSTAMP;
		public virtual Schema Schema
		{
			get
			{
				return JavaCardsRecord._SCHEMA;
			}
		}
		public EdpSimulator.Entities.AfterImageCards afterImage
		{
			get
			{
				return this._afterImage;
			}
			set
			{
				this._afterImage = value;
			}
		}
		public string beforeImage
		{
			get
			{
				return this._beforeImage;
			}
			set
			{
				this._beforeImage = value;
			}
		}
		public string A_ENTTYP
		{
			get
			{
				return this._A_ENTTYP;
			}
			set
			{
				this._A_ENTTYP = value;
			}
		}
		public string A_CCID
		{
			get
			{
				return this._A_CCID;
			}
			set
			{
				this._A_CCID = value;
			}
		}
		public string A_TIMSTAMP
		{
			get
			{
				return this._A_TIMSTAMP;
			}
			set
			{
				this._A_TIMSTAMP = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.afterImage;
			case 1: return this.beforeImage;
			case 2: return this.A_ENTTYP;
			case 3: return this.A_CCID;
			case 4: return this.A_TIMSTAMP;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.afterImage = (EdpSimulator.Entities.AfterImageCards)fieldValue; break;
			case 1: this.beforeImage = (System.String)fieldValue; break;
			case 2: this.A_ENTTYP = (System.String)fieldValue; break;
			case 3: this.A_CCID = (System.String)fieldValue; break;
			case 4: this.A_TIMSTAMP = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
		public string GetTransactionKey() =>
			"CARDS_ID" +
			afterImage.ORIG_PLAS +
			afterImage.TXN_AMT +
			afterImage.TXN_SINAL +
			afterImage.TXN_DT + afterImage.TXN_TM;

		public string GetPartitionValue() => this.GetTransactionKey();
		public string GetCosmosId() => "";

	}
}
