// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EdpSimulator.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	using EdpSimulator;


	public partial class JavaH2hRecord : IEdpRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"H2h\",\"namespace\":\"EdpSimulator.Entities\",\"fields\":[{\"nam" +
				"e\":\"afterImage\",\"type\":{\"type\":\"record\",\"name\":\"AfterImageH2h\",\"namespace\":\"EdpS" +
				"imulator.Entities\",\"fields\":[{\"name\":\"IDMSGBAN_1\",\"type\":\"int\"},{\"name\":\"IDMSGBA" +
				"N_2\",\"type\":\"int\"},{\"name\":\"CONTA_CLI\",\"type\":\"int\"},{\"name\":\"CODMSG_BS\",\"type\":" +
				"\"string\"},{\"name\":\"VERMSG\",\"type\":\"int\"},{\"name\":\"DHMSG\",\"type\":\"int\"},{\"name\":\"" +
				"CODRESPS\",\"type\":\"int\"},{\"name\":\"DT_RECOLHA\",\"type\":\"int\"},{\"name\":\"ESTADO_ANT\"," +
				"\"type\":\"string\"},{\"name\":\"ESTADO_ACT\",\"type\":\"string\"},{\"name\":\"RETURN_CODE\",\"ty" +
				"pe\":\"int\"},{\"name\":\"RETURN_MSG\",\"type\":\"string\"},{\"name\":\"TIPO_PEDIDO\",\"type\":\"i" +
				"nt\"},{\"name\":\"TIP_PAG_SER\",\"type\":\"int\"},{\"name\":\"NIB_ORD\",\"type\":\"string\"},{\"na" +
				"me\":\"ENTIDADE\",\"type\":\"int\"},{\"name\":\"REFERENCIA\",\"type\":\"int\"},{\"name\":\"REF_ESP" +
				"\",\"type\":\"int\"},{\"name\":\"REF_ADICIONAL\",\"type\":\"int\"},{\"name\":\"REF_RESPOSTA\",\"ty" +
				"pe\":\"int\"},{\"name\":\"MONTANTE\",\"type\":\"string\"},{\"name\":\"REDE_ORIGEM\",\"type\":\"str" +
				"ing\"},{\"name\":\"CANAL_ORIGEM\",\"type\":\"string\"},{\"name\":\"USERID_CLI\",\"type\":\"strin" +
				"g\"},{\"name\":\"CAT_NR\",\"type\":\"string\"},{\"name\":\"CAT_CARTAO\",\"type\":\"string\"},{\"na" +
				"me\":\"LOCMORTER\",\"type\":\"string\"},{\"name\":\"CHAVE_TRF\",\"type\":\"string\"},{\"name\":\"A" +
				"PLIC_N\",\"type\":\"string\"},{\"name\":\"ID_LOG_SIBS\",\"type\":\"int\"},{\"name\":\"NR_LOG_SIB" +
				"S\",\"type\":\"int\"},{\"name\":\"NR_CONTRIBUINTE\",\"type\":\"int\"},{\"name\":\"NR_FACTURA\",\"t" +
				"ype\":\"int\"},{\"name\":\"DESCENT\",\"type\":\"string\"},{\"name\":\"TIPSER\",\"type\":\"int\"},{\"" +
				"name\":\"CODMOEDA\",\"type\":\"string\"},{\"name\":\"CODRECS\",\"type\":\"string\"},{\"name\":\"RE" +
				"SP1\",\"type\":\"string\"},{\"name\":\"RESP2\",\"type\":\"string\"},{\"name\":\"BANCO_CLI\",\"type" +
				"\":\"int\"},{\"name\":\"BALCAO_CLI\",\"type\":\"int\"},{\"name\":\"CKD_CLI\",\"type\":\"int\"},{\"na" +
				"me\":\"DH_INS\",\"type\":\"string\"},{\"name\":\"CONFIRMACAO_SIBS\",\"type\":\"string\"},{\"name" +
				"\":\"DH_CONFIRMACAO\",\"type\":\"string\"},{\"name\":\"USERID_ALT\",\"type\":\"string\"},{\"name" +
				"\":\"DH_ALT\",\"type\":\"string\"},{\"name\":\"SIBS_PEDIDO\",\"type\":\"string\"},{\"name\":\"SIBS" +
				"_RESPOSTA\",\"type\":\"string\"},{\"name\":\"MEIO_PAGAMENTO\",\"type\":\"string\"},{\"name\":\"P" +
				"AN_CARTAO\",\"type\":\"int\"},{\"name\":\"FATURA_SIMPLIF\",\"type\":\"string\"},{\"name\":\"RODA" +
				"PE_FAT_SIMP\",\"type\":\"string\"},{\"name\":\"COD_JANELA\",\"type\":\"string\"}]}},{\"name\":\"" +
				"beforeImage\",\"type\":[\"string\",\"null\"]},{\"name\":\"A_ENTTYP\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"nam" +
				"e\":\"A_CCID\",\"type\":\"string\"},{\"name\":\"A_TIMSTAMP\",\"type\":\"string\"}]}");
		private EdpSimulator.Entities.AfterImageH2h _afterImage;
		private string _beforeImage;
		private string _A_ENTTYP;
		private string _A_CCID;
		private string _A_TIMSTAMP;
		public virtual Schema Schema
		{
			get
			{
				return JavaH2hRecord._SCHEMA;
			}
		}
		public EdpSimulator.Entities.AfterImageH2h afterImage
		{
			get
			{
				return this._afterImage;
			}
			set
			{
				this._afterImage = value;
			}
		}
		public string beforeImage
		{
			get
			{
				return this._beforeImage;
			}
			set
			{
				this._beforeImage = value;
			}
		}
		public string A_ENTTYP
		{
			get
			{
				return this._A_ENTTYP;
			}
			set
			{
				this._A_ENTTYP = value;
			}
		}
		public string A_CCID
		{
			get
			{
				return this._A_CCID;
			}
			set
			{
				this._A_CCID = value;
			}
		}
		public string A_TIMSTAMP
		{
			get
			{
				return this._A_TIMSTAMP;
			}
			set
			{
				this._A_TIMSTAMP = value;
			}
		}

		public string GetTransactionKey() =>
			"H2H_ID" + afterImage.IDMSGBAN_2 +
			"DDA" + afterImage.CONTA_CLI +
			"H003" + afterImage.IDMSGBAN_1 +
			afterImage.IDMSGBAN_2;

		public string GetPartitionValue() => this.GetTransactionKey();
		public string GetCosmosId() => Guid.NewGuid().ToString();
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.afterImage;
			case 1: return this.beforeImage;
			case 2: return this.A_ENTTYP;
			case 3: return this.A_CCID;
			case 4: return this.A_TIMSTAMP;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.afterImage = (EdpSimulator.Entities.AfterImageH2h)fieldValue; break;
			case 1: this.beforeImage = (System.String)fieldValue; break;
			case 2: this.A_ENTTYP = (System.String)fieldValue; break;
			case 3: this.A_CCID = (System.String)fieldValue; break;
			case 4: this.A_TIMSTAMP = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
