// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace key.SOURCEDB.CAM00020.CAM20
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	using EdpSimulator;
	public partial class LOGTXN_T : IEdpRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""LOGTXN_T"",""namespace"":""key.SOURCEDB.CAM00020.CAM20"",""fields"":[{""name"":""ACCT_COID"",""default"":"""",""type"":""string""},{""name"":""ACCT_PROD"",""default"":"""",""type"":""string""},{""name"":""ACCT_NBR"",""default"":"""",""type"":""string""},{""name"":""FILE_ORIG"",""default"":"""",""type"":""string""},{""name"":""PSTG_DT"",""default"":"""",""type"":""string""},{""name"":""PSTG_SEQ"",""default"":""0"",""type"":""string""}]}");
		private string _ACCT_COID;
		private string _ACCT_PROD;
		private string _ACCT_NBR;
		private string _FILE_ORIG;
		private string _PSTG_DT;
		private string _PSTG_SEQ;
		public virtual Schema Schema
		{
			get
			{
				return LOGTXN_T._SCHEMA;
			}
		}
		public string ACCT_COID
		{
			get
			{
				return this._ACCT_COID;
			}
			set
			{
				this._ACCT_COID = value;
			}
		}
		public string ACCT_PROD
		{
			get
			{
				return this._ACCT_PROD;
			}
			set
			{
				this._ACCT_PROD = value;
			}
		}
		public string ACCT_NBR
		{
			get
			{
				return this._ACCT_NBR;
			}
			set
			{
				this._ACCT_NBR = value;
			}
		}
		public string FILE_ORIG
		{
			get
			{
				return this._FILE_ORIG;
			}
			set
			{
				this._FILE_ORIG = value;
			}
		}
		public string PSTG_DT
		{
			get
			{
				return this._PSTG_DT;
			}
			set
			{
				this._PSTG_DT = value;
			}
		}
		public string PSTG_SEQ
		{
			get
			{
				return this._PSTG_SEQ;
			}
			set
			{
				this._PSTG_SEQ = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ACCT_COID;
			case 1: return this.ACCT_PROD;
			case 2: return this.ACCT_NBR;
			case 3: return this.FILE_ORIG;
			case 4: return this.PSTG_DT;
			case 5: return this.PSTG_SEQ;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ACCT_COID = (System.String)fieldValue; break;
			case 1: this.ACCT_PROD = (System.String)fieldValue; break;
			case 2: this.ACCT_NBR = (System.String)fieldValue; break;
			case 3: this.FILE_ORIG = (System.String)fieldValue; break;
			case 4: this.PSTG_DT = (System.String)fieldValue; break;
			case 5: this.PSTG_SEQ = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}

		public string GetPartitionValue() => "";


		public string GetCosmosId() => "";
	}
}
