// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace key.SOURCEDB.DEP000PA.DEPPA
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	using EdpSimulator;
	public partial class HMV_DDA : IEdpRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"HMV_DDA\",\"namespace\":\"key.SOURCEDB.DEP000PA.DEPPA\",\"fiel" +
				"ds\":[{\"name\":\"HDDA_KEY_CONTA\",\"type\":\"string\"},{\"name\":\"HDDA_KEY_DATA_LANCAMENTO" +
				"\",\"type\":\"string\"},{\"name\":\"HDDA_KEY_DATA_HORA\",\"type\":\"string\"}]}");
		private string _HDDA_KEY_CONTA;
		private string _HDDA_KEY_DATA_LANCAMENTO;
		private string _HDDA_KEY_DATA_HORA;
		public virtual Schema Schema
		{
			get
			{
				return HMV_DDA._SCHEMA;
			}
		}
		public string HDDA_KEY_CONTA
		{
			get
			{
				return this._HDDA_KEY_CONTA;
			}
			set
			{
				this._HDDA_KEY_CONTA = value;
			}
		}
		public string HDDA_KEY_DATA_LANCAMENTO
		{
			get
			{
				return this._HDDA_KEY_DATA_LANCAMENTO;
			}
			set
			{
				this._HDDA_KEY_DATA_LANCAMENTO = value;
			}
		}
		public string HDDA_KEY_DATA_HORA
		{
			get
			{
				return this._HDDA_KEY_DATA_HORA;
			}
			set
			{
				this._HDDA_KEY_DATA_HORA = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.HDDA_KEY_CONTA;
			case 1: return this.HDDA_KEY_DATA_LANCAMENTO;
			case 2: return this.HDDA_KEY_DATA_HORA;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.HDDA_KEY_CONTA = (System.String)fieldValue; break;
			case 1: this.HDDA_KEY_DATA_LANCAMENTO = (System.String)fieldValue; break;
			case 2: this.HDDA_KEY_DATA_HORA = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}

		public string GetPartitionValue() => "";


		public string GetCosmosId() => "";
	}
}
